"""Core EPIRO models."""

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional

from geoalchemy2 import Geometry
from sqlalchemy import (
    Boolean,
    Column,
    Computed,
    Date,
    DateTime,
)
from sqlalchemy import Enum as SQLEnum
from sqlalchemy import (
    ForeignKey,
    Index,
    Integer,
    Numeric,
    Sequence,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampedModel


def _enum_values(enum_cls: type[Enum]) -> list[str]:
    """Persist the enum's value rather than its member name.

    SQLAlchemy stores ``Enum.name`` by default, which would write "SUPER_ADMIN"
    while every API payload and client uses "super_admin". Storing values keeps
    the database and the wire format identical.
    """
    return [str(member.value) for member in enum_cls]


# The text search configuration every search vector is built with. Stored
# alongside the vectors so the query side cannot drift from the index side: a
# tsquery parsed with a different configuration silently stops matching.
SEARCH_CONFIG = "english"


def _search_vector(*weighted: tuple[str, str]) -> Computed:
    """A stored tsvector over the named columns, each with a ranking weight.

    Generated by the database rather than maintained by the application. A
    trigger the application forgets to fire, or a write path that skips the
    update, leaves a row that has quietly stopped being findable; a generated
    column cannot get out of step with the row it describes.

    Weights order the result: 'A' for a title or identifier, 'B' for the main
    body, 'C' for supporting text.
    """
    expression = " || ".join(
        # Quoted because a column name may collide with a keyword: scenario
        # has one called "trigger".
        f"setweight(to_tsvector('{SEARCH_CONFIG}', coalesce(\"{column}\", '')), '{weight}')"
        for column, weight in weighted
    )
    return Computed(expression, persisted=True)


class Role(str, Enum):
    """User roles."""

    SUPER_ADMIN = "super_admin"
    EXECUTIVE = "executive"
    EDITOR = "editor"
    EVIDENCE_MANAGER = "evidence_manager"
    RESEARCHER = "researcher"
    FIELD_OFFICER = "field_officer"
    VERIFIER = "verifier"
    INTEGRITY_ANALYST = "integrity_analyst"
    CONTENT_MANAGER = "content_manager"
    MEDIA_MANAGER = "media_manager"
    TRANSLATOR = "translator"
    APPROVER = "approver"
    ANALYST = "analyst"
    PUBLIC_USER = "public_user"


class EvidenceStatus(str, Enum):
    """Evidence lifecycle statuses."""

    DRAFT = "draft"
    SUBMITTED = "submitted"
    UNDER_REVIEW = "under_review"
    VERIFIED = "verified"
    APPROVED = "approved"
    PUBLISHED = "published"
    ARCHIVED = "archived"
    REJECTED = "rejected"


class StoryStatus(str, Enum):
    """Editorial states a story moves through.

    Spec section 36 puts review and approval between drafting and publication.
    A free-text status could not express that: the only value anything ever set
    was "published", so approval and publication were the same act.
    """

    DRAFT = "draft"
    IN_REVIEW = "in_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class QuestionStatus(str, Enum):
    """Question workflow statuses."""

    NEW = "new"
    TRIAGED = "triaged"
    RESEARCHING = "researching"
    VERIFIED = "verified"
    RESPONSE_DRAFTED = "response_drafted"
    APPROVED = "approved"
    PUBLISHED = "published"
    CLOSED = "closed"


class IntegritySignalPriority(str, Enum):
    """Information integrity signal priority."""

    LOW_RISK = "low_risk"
    EMERGING = "emerging"
    MATERIAL = "material"
    CRISIS = "crisis"
    NATIONAL = "national"


class ReadinessStatus(str, Enum):
    """Readiness matrix status."""

    GREEN = "green"
    AMBER = "amber"
    RED = "red"
    BLACK = "black"


class ProjectStatus(str, Enum):
    """Project lifecycle states."""

    PROPOSED = "proposed"
    PLANNED = "planned"
    ACTIVE = "active"
    DELAYED = "delayed"
    COMPLETED = "completed"
    SUSPENDED = "suspended"
    ARCHIVED = "archived"


class MilestoneStatus(str, Enum):
    """Milestone states."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    MISSED = "missed"


class ApprovalDecision(str, Enum):
    """Outcomes an approval round can reach.

    Rejection and a request for changes are recorded like any other decision:
    the history of what was turned down is as much a part of accountability as
    what went through.
    """

    APPROVED = "approved"
    REJECTED = "rejected"
    CHANGES_REQUESTED = "changes_requested"


class SourceType(str, Enum):
    """Kinds of source the registry accepts (spec section 11)."""

    OFFICIAL_DOCUMENT = "official_document"
    GOVERNMENT_DATA = "government_data"
    RESEARCH = "research"
    FIELD_REPORT = "field_report"
    INTERVIEW = "interview"
    MEDIA_REPORT = "media_report"
    DATASET = "dataset"
    PHOTOGRAPH = "photograph"
    VIDEO = "video"
    AUDIO = "audio"
    USER_SUBMISSION = "user_submission"
    INSTITUTIONAL_SOURCE = "institutional_source"


class VerificationState(str, Enum):
    """Transparent verification states.

    There is no "true" here by design: spec section 11 forbids automatically
    labelling a source true, so the states describe how far review has got and
    what it found, never that the content is fact.
    """

    UNVERIFIED = "unverified"
    IN_REVIEW = "in_review"
    VERIFIED = "verified"
    DISPUTED = "disputed"
    REJECTED = "rejected"


class SourceReliability(str, Enum):
    """How much weight a source's track record earns it.

    A stated classification with a written rationale, rather than the numeric
    score it replaces, which had no defined methodology.
    """

    UNKNOWN = "unknown"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class GeographyLevel(str, Enum):
    """Tiers of the administrative hierarchy."""

    COUNTRY = "country"
    REGION = "region"
    STATE = "state"
    LGA = "lga"
    WARD = "ward"
    COMMUNITY = "community"


# Coarsest first. A node's parent must sit strictly above it here, which
# prevents inversions without forcing every country to use every tier: not
# every country has a region layer between country and state.
GEOGRAPHY_LEVEL_ORDER: tuple[GeographyLevel, ...] = (
    GeographyLevel.COUNTRY,
    GeographyLevel.REGION,
    GeographyLevel.STATE,
    GeographyLevel.LGA,
    GeographyLevel.WARD,
    GeographyLevel.COMMUNITY,
)


def geography_level_rank(level: GeographyLevel) -> int:
    """Position of a level in the hierarchy, coarsest first."""
    return GEOGRAPHY_LEVEL_ORDER.index(level)


# Backs the human-readable evidence reference. Declared on the metadata so
# Alembic creates it alongside the tables.
evidence_reference_seq = Sequence("evidence_reference_seq", metadata=Base.metadata)


# Association tables
user_organisation = Table(
    "user_organisation",
    Base.metadata,
    Column("user_id", UUID(as_uuid=True), ForeignKey("user.id"), primary_key=True),
    Column(
        "organisation_id",
        UUID(as_uuid=True),
        ForeignKey("organisation.id"),
        primary_key=True,
    ),
    Column(
        "role",
        SQLEnum(Role, values_callable=_enum_values),
        nullable=False,
        default=Role.PUBLIC_USER,
    ),
)

programme_thematic = Table(
    "programme_thematic",
    Base.metadata,
    Column("programme_id", UUID(as_uuid=True), ForeignKey("programme.id"), primary_key=True),
    Column(
        "thematic_id",
        UUID(as_uuid=True),
        ForeignKey("thematic_area.id"),
        primary_key=True,
    ),
)


class Organisation(TimestampedModel):
    """Organisation model."""

    __tablename__ = "organisation"

    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[Optional[str]] = mapped_column(Text)
    country: Mapped[str] = mapped_column(String(2), default="NG", nullable=False)
    timezone: Mapped[str] = mapped_column(String(50), default="Africa/Lagos", nullable=False)
    logo_url: Mapped[Optional[str]] = mapped_column(String(500))
    website: Mapped[Optional[str]] = mapped_column(String(500))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    users: Mapped[list["User"]] = relationship(
        secondary=user_organisation, back_populates="organisations"
    )
    programmes: Mapped[list["Programme"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    projects: Mapped[list["Project"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    evidence_items: Mapped[list["Evidence"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    sources: Mapped[list["Source"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    stories: Mapped[list["Story"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_organisation_code", "code"),
        Index("idx_organisation_active", "is_active"),
    )


class User(TimestampedModel):
    """User model."""

    __tablename__ = "user"

    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # Platform-level administration, distinct from the SUPER_ADMIN role, which
    # confers full rights within one organisation only.
    is_superuser: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    last_login: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    phone: Mapped[Optional[str]] = mapped_column(String(20))
    avatar_url: Mapped[Optional[str]] = mapped_column(String(500))
    timezone: Mapped[Optional[str]] = mapped_column(String(50))
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    preferences: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisations: Mapped[list["Organisation"]] = relationship(
        secondary=user_organisation, back_populates="users"
    )

    __table_args__ = (
        Index("idx_user_email", "email"),
        Index("idx_user_active", "is_active"),
        # Directory lookup matches on any part of a name or address, which a
        # B-tree index cannot serve: ILIKE '%term%' has no usable prefix.
        Index(
            "idx_user_name_trgm",
            "email",
            "first_name",
            "last_name",
            postgresql_using="gin",
            postgresql_ops={
                "email": "gin_trgm_ops",
                "first_name": "gin_trgm_ops",
                "last_name": "gin_trgm_ops",
            },
        ),
    )


class Geography(TimestampedModel):
    """A node in the Country / Region / State / LGA / Ward / Community tree.

    Reference data shared across organisations rather than tenant-scoped: the
    administrative map of a country is the same for every organisation working
    in it, and duplicating it per tenant would make comparison across tenants
    impossible.
    """

    # Not "geography": PostGIS defines a type of that name, and a table would
    # collide with it. Do not rename this to match the class.
    __tablename__ = "geographic_area"

    parent_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id", ondelete="RESTRICT"), nullable=True
    )
    level: Mapped[GeographyLevel] = mapped_column(
        SQLEnum(GeographyLevel, values_callable=_enum_values), nullable=False
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    # Administrative code where one exists, such as an ISO country code or a
    # national statistics office identifier.
    code: Mapped[Optional[str]] = mapped_column(String(32))
    centroid: Mapped[Optional[Any]] = mapped_column(Geometry("POINT", srid=4326), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    parent: Mapped[Optional["Geography"]] = relationship(
        remote_side="Geography.id", back_populates="children"
    )
    children: Mapped[list["Geography"]] = relationship(back_populates="parent")
    projects: Mapped[list["Project"]] = relationship(back_populates="geography")
    locations: Mapped[list["Location"]] = relationship(back_populates="geography")

    __table_args__ = (
        UniqueConstraint("parent_id", "level", "name", name="uq_geography_parent_level_name"),
        # Postgres treats NULLs as distinct, so the constraint above does not
        # cover root nodes. This closes that gap for countries.
        Index(
            "uq_geographic_area_root_level_name",
            "level",
            "name",
            unique=True,
            postgresql_where=text("parent_id IS NULL"),
        ),
        Index("idx_geographic_area_parent_id", "parent_id"),
        Index("idx_geographic_area_level", "level"),
        Index(
            "idx_geographic_area_name_trgm",
            "name",
            postgresql_using="gin",
            postgresql_ops={"name": "gin_trgm_ops"},
        ),
    )


class ThematicArea(TimestampedModel):
    """Thematic stream configuration."""

    __tablename__ = "thematic_area"

    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[Optional[str]] = mapped_column(Text)
    icon: Mapped[Optional[str]] = mapped_column(String(50))
    color: Mapped[Optional[str]] = mapped_column(String(7))
    order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    programmes: Mapped[list["Programme"]] = relationship(
        secondary=programme_thematic, back_populates="thematic_areas"
    )
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="thematic_area")

    __table_args__ = (
        Index("idx_thematic_code", "code"),
        Index("idx_thematic_active", "is_active"),
        Index(
            "idx_thematic_name_trgm",
            "name",
            postgresql_using="gin",
            postgresql_ops={"name": "gin_trgm_ops"},
        ),
    )


class Programme(TimestampedModel):
    """Programme model."""

    __tablename__ = "programme"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    code: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    start_date: Mapped[Optional[date]] = mapped_column(Date)
    end_date: Mapped[Optional[date]] = mapped_column(Date)
    budget: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 2))
    budget_currency: Mapped[Optional[str]] = mapped_column(String(3))
    status: Mapped[str] = mapped_column(String(50), default="active", nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="programmes")
    projects: Mapped[list["Project"]] = relationship(
        back_populates="programme", cascade="all, delete-orphan"
    )
    thematic_areas: Mapped[list["ThematicArea"]] = relationship(
        secondary=programme_thematic, back_populates="programmes"
    )

    __table_args__ = (
        UniqueConstraint("organisation_id", "code", name="uq_programme_org_code"),
        Index("idx_programme_org_id", "organisation_id"),
    )


class Project(TimestampedModel):
    """Project model."""

    __tablename__ = "project"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    code: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    programme_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("programme.id"), nullable=True
    )
    start_date: Mapped[Optional[date]] = mapped_column(Date)
    end_date: Mapped[Optional[date]] = mapped_column(Date)
    budget: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 2))
    budget_currency: Mapped[Optional[str]] = mapped_column(String(3))
    status: Mapped[ProjectStatus] = mapped_column(
        SQLEnum(ProjectStatus, values_callable=_enum_values),
        default=ProjectStatus.PROPOSED,
        nullable=False,
    )
    # Replaces the former location_state / location_lga / location_community
    # strings, which could not be filtered on reliably or rolled up.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    implementing_org: Mapped[Optional[str]] = mapped_column(String(255))
    funding_source: Mapped[Optional[str]] = mapped_column(String(255))
    sector: Mapped[Optional[str]] = mapped_column(String(100))
    target_beneficiaries: Mapped[Optional[int]] = mapped_column(Integer)
    actual_completion: Mapped[Optional[date]] = mapped_column(Date)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="projects")
    programme: Mapped[Optional["Programme"]] = relationship(back_populates="projects")
    geography: Mapped[Optional["Geography"]] = relationship(back_populates="projects")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="project")
    locations: Mapped[list["Location"]] = relationship(back_populates="project")
    milestones: Mapped[list["Milestone"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    indicators: Mapped[list["Indicator"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("name", "A"), ("code", "A"), ("description", "B")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        UniqueConstraint("organisation_id", "code", name="uq_project_org_code"),
        Index("idx_project_org_id", "organisation_id"),
        Index("idx_project_programme_id", "programme_id"),
        Index("idx_project_geography_id", "geography_id"),
        Index("idx_project_status", "status"),
        Index("idx_project_search", "search_vector", postgresql_using="gin"),
    )


class Milestone(TimestampedModel):
    """A dated checkpoint within a project."""

    __tablename__ = "milestone"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    due_date: Mapped[Optional[date]] = mapped_column(Date)
    completed_date: Mapped[Optional[date]] = mapped_column(Date)
    status: Mapped[MilestoneStatus] = mapped_column(
        SQLEnum(MilestoneStatus, values_callable=_enum_values),
        default=MilestoneStatus.PENDING,
        nullable=False,
    )
    sequence: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Relationships
    project: Mapped["Project"] = relationship(back_populates="milestones")

    __table_args__ = (
        Index("idx_milestone_project_id", "project_id"),
        Index("idx_milestone_status", "status"),
    )


class Indicator(TimestampedModel):
    """A measurable quantity a project is expected to move.

    Baseline, target and current value live here so that evidence can record a
    measurement against a named indicator rather than restating the definition
    on every record.
    """

    __tablename__ = "indicator"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id", ondelete="CASCADE"), nullable=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    unit: Mapped[Optional[str]] = mapped_column(String(50))
    baseline_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    baseline_date: Mapped[Optional[date]] = mapped_column(Date)
    target_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    target_date: Mapped[Optional[date]] = mapped_column(Date)
    current_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    current_value_date: Mapped[Optional[date]] = mapped_column(Date)

    # Relationships
    project: Mapped[Optional["Project"]] = relationship(back_populates="indicators")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="indicator")

    __table_args__ = (
        Index("idx_indicator_organisation_id", "organisation_id"),
        Index("idx_indicator_project_id", "project_id"),
    )


class Location(TimestampedModel):
    """Geographic location model."""

    __tablename__ = "location"

    # Nullable so a location can be recorded for evidence that is not tied to a
    # project.
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=True
    )
    # The administrative area this point falls within. A Location is a
    # specific place; a Geography is the area it sits inside.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    latitude: Mapped[Optional[Decimal]] = mapped_column(Numeric(9, 6))
    longitude: Mapped[Optional[Decimal]] = mapped_column(Numeric(9, 6))
    geom: Mapped[Optional[Any]] = mapped_column(Geometry("POINT", srid=4326), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text)

    # Relationships
    project: Mapped[Optional["Project"]] = relationship(back_populates="locations")
    geography: Mapped[Optional["Geography"]] = relationship(back_populates="locations")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="location")

    __table_args__ = (
        Index("idx_location_project_id", "project_id"),
        Index("idx_location_geography_id", "geography_id"),
    )


class Source(TimestampedModel):
    """Source registry model."""

    __tablename__ = "source"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    source_type: Mapped[SourceType] = mapped_column(
        SQLEnum(SourceType, values_callable=_enum_values), nullable=False
    )
    url: Mapped[Optional[str]] = mapped_column(String(500))
    description: Mapped[Optional[str]] = mapped_column(Text)

    # Who published it, as distinct from the tenant that recorded it.
    publisher: Mapped[Optional[str]] = mapped_column(String(255))
    author: Mapped[Optional[str]] = mapped_column(String(255))
    publication_date: Mapped[Optional[date]] = mapped_column(Date)

    # Provenance
    document_url: Mapped[Optional[str]] = mapped_column(String(500))
    # Hash of the stored document, so a later copy can be shown to be the same
    # artefact that was reviewed.
    document_hash: Mapped[Optional[str]] = mapped_column(String(128))
    provenance: Mapped[Optional[str]] = mapped_column(Text)

    # Governance. There is deliberately no boolean "verified" and no numeric
    # credibility score: spec section 11 requires transparent states rather
    # than a source being labelled true, and section 7 rules out unexplained
    # scores.
    verification_state: Mapped[VerificationState] = mapped_column(
        SQLEnum(VerificationState, values_callable=_enum_values),
        default=VerificationState.UNVERIFIED,
        nullable=False,
    )
    reliability: Mapped[SourceReliability] = mapped_column(
        SQLEnum(SourceReliability, values_callable=_enum_values),
        default=SourceReliability.UNKNOWN,
        nullable=False,
    )
    reliability_rationale: Mapped[Optional[str]] = mapped_column(Text)
    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    review_date: Mapped[Optional[date]] = mapped_column(Date)
    # When this assessment should be revisited. A source verified years ago is
    # not thereby still verified.
    next_review_date: Mapped[Optional[date]] = mapped_column(Date)

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="sources")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="source")

    __table_args__ = (
        Index("idx_source_organisation_id", "organisation_id"),
        Index("idx_source_type", "source_type"),
        Index("idx_source_verification_state", "verification_state"),
    )


class Evidence(TimestampedModel):
    """Evidence registry model."""

    __tablename__ = "evidence"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=True
    )
    location_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.id"), nullable=True
    )
    source_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("source.id"), nullable=False
    )
    thematic_area_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("thematic_area.id"), nullable=True
    )
    # Evidence can be placed on the map without belonging to a project site.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    indicator_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("indicator.id"), nullable=True
    )

    # Permanent, human-readable identifier. Generated by the database so it is
    # assigned exactly once, at insert, and cannot drift: an evidence record
    # must stay citable by the same reference for its whole life.
    reference: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        unique=True,
        server_default=text(
            "'EV-' || to_char(now(), 'YYYY') || '-' "
            "|| lpad(nextval('evidence_reference_seq')::text, 6, '0')"
        ),
    )

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[EvidenceStatus] = mapped_column(
        SQLEnum(EvidenceStatus, values_callable=_enum_values),
        default=EvidenceStatus.DRAFT,
        nullable=False,
    )
    evidence_date: Mapped[Optional[date]] = mapped_column(Date)

    # Evidence details
    beneficiaries: Mapped[Optional[int]] = mapped_column(Integer)
    outcome: Mapped[Optional[str]] = mapped_column(Text)
    confidence_level: Mapped[Optional[int]] = mapped_column(Integer)
    # The measurement this record contributes, against indicator_id. The
    # indicator holds the definition, baseline and target; evidence holds an
    # observation of it at a point in time.
    measured_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))

    # Files and media
    document_url: Mapped[Optional[str]] = mapped_column(String(500))
    image_urls: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)
    video_urls: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)

    # Verification
    verification_status: Mapped[str] = mapped_column(
        String(50), default="unverified", nullable=False
    )
    verified_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    verified_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    verifier_notes: Mapped[Optional[str]] = mapped_column(Text)

    # Approval
    approval_status: Mapped[str] = mapped_column(String(50), default="pending", nullable=False)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    # Metadata
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)
    tags: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="evidence_items")
    project: Mapped[Optional["Project"]] = relationship(back_populates="evidence_items")
    location: Mapped[Optional["Location"]] = relationship(back_populates="evidence_items")
    source: Mapped["Source"] = relationship(back_populates="evidence_items")
    geography: Mapped[Optional["Geography"]] = relationship()
    indicator: Mapped[Optional["Indicator"]] = relationship(back_populates="evidence_items")
    thematic_area: Mapped[Optional["ThematicArea"]] = relationship(back_populates="evidence_items")
    stories: Mapped[list["Story"]] = relationship(back_populates="evidence")
    audit_logs: Mapped[list["AuditLog"]] = relationship(back_populates="evidence")

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(
            ("reference", "A"),
            ("title", "A"),
            ("description", "B"),
            ("outcome", "C"),
        ),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_evidence_organisation_id", "organisation_id"),
        Index("idx_evidence_status", "status"),
        Index("idx_evidence_project_id", "project_id"),
        Index("idx_evidence_search", "search_vector", postgresql_using="gin"),
    )


class Story(TimestampedModel):
    """Public information story model."""

    __tablename__ = "story"

    # Tenancy is carried explicitly rather than inferred through evidence, so
    # story queries can be scoped without a join.
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    evidence_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence.id"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    headline: Mapped[Optional[str]] = mapped_column(String(500))
    body: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text)
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    status: Mapped[StoryStatus] = mapped_column(
        SQLEnum(StoryStatus, values_callable=_enum_values),
        default=StoryStatus.DRAFT,
        nullable=False,
    )
    featured: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    published_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="stories")
    evidence: Mapped["Evidence"] = relationship(back_populates="stories")

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(
            ("title", "A"),
            ("headline", "A"),
            ("summary", "B"),
            ("body", "C"),
        ),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_story_evidence_id", "evidence_id"),
        Index("idx_story_organisation_id", "organisation_id"),
        Index("idx_story_status", "status"),
        Index("idx_story_search", "search_vector", postgresql_using="gin"),
    )


class Question(TimestampedModel):
    """Citizen question model."""

    __tablename__ = "question"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    category: Mapped[Optional[str]] = mapped_column(String(100))
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    # Free text as the submitter typed it. geography_id is the resolved area,
    # set during triage; keeping both preserves what was actually said.
    location_state: Mapped[Optional[str]] = mapped_column(String(50))
    location_lga: Mapped[Optional[str]] = mapped_column(String(100))
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    is_anonymous: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    submitter_email: Mapped[Optional[str]] = mapped_column(String(255))
    status: Mapped[QuestionStatus] = mapped_column(
        SQLEnum(QuestionStatus, values_callable=_enum_values),
        default=QuestionStatus.NEW,
        nullable=False,
    )
    assigned_to: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    response: Mapped[Optional[str]] = mapped_column(Text)
    # Recorded separately from updated_by so approval can require a different
    # person from whoever drafted the response.
    responded_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    response_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    is_published: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # The body answering the question, once it has been triaged to one.
    organisation: Mapped[Optional["Organisation"]] = relationship()

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("question_text", "A"), ("response", "B"), ("category", "C")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_question_status", "status"),
        Index("idx_question_organisation_id", "organisation_id"),
        Index("idx_question_search", "search_vector", postgresql_using="gin"),
    )


class IntegritySignal(TimestampedModel):
    """Information integrity signal model."""

    __tablename__ = "integrity_signal"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    claim: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[Optional[str]] = mapped_column(String(255))
    priority: Mapped[IntegritySignalPriority] = mapped_column(
        SQLEnum(IntegritySignalPriority, values_callable=_enum_values),
        default=IntegritySignalPriority.LOW_RISK,
        nullable=False,
    )
    status: Mapped[str] = mapped_column(String(50), default="new", nullable=False)
    assigned_to: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    verification_result: Mapped[Optional[str]] = mapped_column(Text)
    response: Mapped[Optional[str]] = mapped_column(Text)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )

    __table_args__ = (
        Index("idx_integrity_priority", "priority"),
        Index("idx_integrity_status", "status"),
    )


class Scenario(TimestampedModel):
    """Readiness scenario model."""

    __tablename__ = "scenario"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[Optional[str]] = mapped_column(String(50))
    description: Mapped[Optional[str]] = mapped_column(Text)
    trigger: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[ReadinessStatus] = mapped_column(
        SQLEnum(ReadinessStatus, values_callable=_enum_values),
        default=ReadinessStatus.GREEN,
        nullable=False,
    )
    owner: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    playbook_url: Mapped[Optional[str]] = mapped_column(String(500))
    last_drill_date: Mapped[Optional[date]] = mapped_column(Date)

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("name", "A"), ("description", "B"), ("trigger", "C")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_scenario_status", "status"),
        Index("idx_scenario_search", "search_vector", postgresql_using="gin"),
    )


class ApprovalRecord(TimestampedModel):
    """One approval decision, kept whatever the outcome.

    Spec section 36 requires approvals to store the reviewer, timestamp,
    decision, comments and version. Holding only the latest approver on the
    record itself loses every rejection and every earlier round, which is
    exactly the history a reviewer needs.

    Addressed by entity_type and entity_id rather than a foreign key per kind,
    so evidence, stories and questions share one trail.
    """

    __tablename__ = "approval_record"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # The version the decision was made against, so a later edit does not make
    # the decision look like it covered content it never saw.
    entity_version: Mapped[Optional[int]] = mapped_column(Integer)

    decision: Mapped[ApprovalDecision] = mapped_column(
        SQLEnum(ApprovalDecision, values_callable=_enum_values), nullable=False
    )
    reviewer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=False
    )
    decided_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    comments: Mapped[Optional[str]] = mapped_column(Text)

    __table_args__ = (
        Index("idx_approval_entity", "entity_type", "entity_id"),
        Index("idx_approval_organisation_id", "organisation_id"),
        Index("idx_approval_reviewer_id", "reviewer_id"),
    )


class AuditLog(TimestampedModel):
    """Audit logging model."""

    __tablename__ = "audit_log"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    evidence_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence.id"), nullable=True
    )
    action: Mapped[str] = mapped_column(String(255), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    old_values: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB)
    new_values: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45))
    user_agent: Mapped[Optional[str]] = mapped_column(String(500))

    # Relationships
    evidence: Mapped[Optional["Evidence"]] = relationship(back_populates="audit_logs")

    __table_args__ = (
        Index("idx_audit_organisation_id", "organisation_id"),
        Index("idx_audit_user_id", "user_id"),
        Index("idx_audit_action", "action"),
    )
