"""Core EPIRO models."""

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, List, Optional

from geoalchemy2 import Geometry
from sqlalchemy import (
    Boolean,
    Column,
    Computed,
    Date,
    DateTime,
)
from sqlalchemy import Enum as SQLEnum
from sqlalchemy import (
    ForeignKey,
    Index,
    Integer,
    Numeric,
    Sequence,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampedModel


def _enum_values(enum_cls: type[Enum]) -> list[str]:
    """Persist the enum's value rather than its member name.

    SQLAlchemy stores ``Enum.name`` by default, which would write "SUPER_ADMIN"
    while every API payload and client uses "super_admin". Storing values keeps
    the database and the wire format identical.
    """
    return [str(member.value) for member in enum_cls]


# The text search configuration every search vector is built with. Stored
# alongside the vectors so the query side cannot drift from the index side: a
# tsquery parsed with a different configuration silently stops matching.
SEARCH_CONFIG = "english"


def _search_vector(*weighted: tuple[str, str]) -> Computed:
    """A stored tsvector over the named columns, each with a ranking weight.

    Generated by the database rather than maintained by the application. A
    trigger the application forgets to fire, or a write path that skips the
    update, leaves a row that has quietly stopped being findable; a generated
    column cannot get out of step with the row it describes.

    Weights order the result: 'A' for a title or identifier, 'B' for the main
    body, 'C' for supporting text.
    """
    expression = " || ".join(
        # Quoted because a column name may collide with a keyword: scenario
        # has one called "trigger".
        f"setweight(to_tsvector('{SEARCH_CONFIG}', coalesce(\"{column}\", '')), '{weight}')"
        for column, weight in weighted
    )
    return Computed(expression, persisted=True)


class Role(str, Enum):
    """User roles."""

    SUPER_ADMIN = "super_admin"
    EXECUTIVE = "executive"
    EDITOR = "editor"
    EVIDENCE_MANAGER = "evidence_manager"
    RESEARCHER = "researcher"
    FIELD_OFFICER = "field_officer"
    VERIFIER = "verifier"
    INTEGRITY_ANALYST = "integrity_analyst"
    CONTENT_MANAGER = "content_manager"
    MEDIA_MANAGER = "media_manager"
    TRANSLATOR = "translator"
    APPROVER = "approver"
    ANALYST = "analyst"
    PUBLIC_USER = "public_user"


class EvidenceStatus(str, Enum):
    """Evidence lifecycle statuses."""

    DRAFT = "draft"
    SUBMITTED = "submitted"
    UNDER_REVIEW = "under_review"
    VERIFIED = "verified"
    APPROVED = "approved"
    PUBLISHED = "published"
    ARCHIVED = "archived"
    REJECTED = "rejected"


class StoryStatus(str, Enum):
    """Editorial states a story moves through.

    Spec section 36 puts review and approval between drafting and publication.
    A free-text status could not express that: the only value anything ever set
    was "published", so approval and publication were the same act.
    """

    DRAFT = "draft"
    IN_REVIEW = "in_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class QuestionStatus(str, Enum):
    """Question workflow statuses."""

    NEW = "new"
    TRIAGED = "triaged"
    RESEARCHING = "researching"
    VERIFIED = "verified"
    RESPONSE_DRAFTED = "response_drafted"
    APPROVED = "approved"
    PUBLISHED = "published"
    CLOSED = "closed"


class IntegritySignalPriority(str, Enum):
    """Information integrity signal priority."""

    LOW_RISK = "low_risk"
    EMERGING = "emerging"
    MATERIAL = "material"
    CRISIS = "crisis"
    NATIONAL = "national"


class IntegritySignalStatus(str, Enum):
    """States an integrity signal moves through (spec sections 25-26).

    The previous column was free text with a default of "new" and nothing that
    ever changed it, so no signal could move at all.
    """

    NEW = "new"
    ASSESSING = "assessing"
    ASSESSED = "assessed"
    APPROVED = "approved"
    PUBLISHED = "published"
    WITHDRAWN = "withdrawn"
    CLOSED = "closed"


class IntegrityFinding(str, Enum):
    """What an assessment concluded **about a claim**.

    Every value describes the information, never the people carrying it. Spec
    section 4 forbids profiling citizens, and a finding about a person is what
    that prohibition is for: the platform records that something circulating is
    false, not who is gullible enough to repeat it.

    ``UNRESOLVED`` is deliberately available and deliberately publishable. An
    assessment that could not settle a claim has to be able to say so; the
    alternative is a system in which the only recordable outcome is a verdict,
    which is how unverified verdicts get recorded.
    """

    ACCURATE = "accurate"
    MISLEADING = "misleading"
    OUT_OF_CONTEXT = "out_of_context"
    FALSE = "false"
    UNSUBSTANTIATED = "unsubstantiated"
    UNRESOLVED = "unresolved"


class ReadinessStatus(str, Enum):
    """How ready an organisation is for one scenario (spec sections 28-31).

    Ordered worst-last. ``READINESS_SEVERITY`` gives the ordering a number so
    that "no better than" comparisons are made against one definition rather
    than re-derived at each call site.
    """

    GREEN = "green"
    AMBER = "amber"
    RED = "red"
    BLACK = "black"


# Severity order, worst highest. A declared status may be this bad or worse
# than the evidence supports, never better — see services/readiness.py.
READINESS_SEVERITY = {
    ReadinessStatus.GREEN: 0,
    ReadinessStatus.AMBER: 1,
    ReadinessStatus.RED: 2,
    ReadinessStatus.BLACK: 3,
}


class DrillStatus(str, Enum):
    """States a rehearsal of a scenario moves through."""

    SCHEDULED = "scheduled"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class MissionStatus(str, Enum):
    """States a field mission moves through (spec section 18)."""

    PLANNED = "planned"
    APPROVED = "approved"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class SafetyState(str, Enum):
    """What a field team last reported about its own safety.

    Deliberately a **state**, not a position. See the FieldMission docstring:
    the platform records that a team is safe, not where each person is.
    """

    SAFE = "safe"
    DELAYED = "delayed"
    ASSISTANCE_REQUIRED = "assistance_required"


class FindingSeverity(str, Enum):
    """How badly a drill finding affects the ability to respond.

    ``CRITICAL`` is the level that holds a scenario's readiness down until it
    is resolved: a gap that would stop the response working is not something an
    organisation may declare its way past.
    """

    OBSERVATION = "observation"
    MINOR = "minor"
    MAJOR = "major"
    CRITICAL = "critical"


class ProjectStatus(str, Enum):
    """Project lifecycle states."""

    PROPOSED = "proposed"
    PLANNED = "planned"
    ACTIVE = "active"
    DELAYED = "delayed"
    COMPLETED = "completed"
    SUSPENDED = "suspended"
    ARCHIVED = "archived"


class MilestoneStatus(str, Enum):
    """Milestone states."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    MISSED = "missed"


class ApprovalDecision(str, Enum):
    """Outcomes an approval round can reach.

    Rejection and a request for changes are recorded like any other decision:
    the history of what was turned down is as much a part of accountability as
    what went through.
    """

    APPROVED = "approved"
    REJECTED = "rejected"
    CHANGES_REQUESTED = "changes_requested"


class SourceType(str, Enum):
    """Kinds of source the registry accepts (spec section 11)."""

    OFFICIAL_DOCUMENT = "official_document"
    GOVERNMENT_DATA = "government_data"
    RESEARCH = "research"
    FIELD_REPORT = "field_report"
    INTERVIEW = "interview"
    MEDIA_REPORT = "media_report"
    DATASET = "dataset"
    PHOTOGRAPH = "photograph"
    VIDEO = "video"
    AUDIO = "audio"
    USER_SUBMISSION = "user_submission"
    INSTITUTIONAL_SOURCE = "institutional_source"


class VerificationState(str, Enum):
    """Transparent verification states.

    There is no "true" here by design: spec section 11 forbids automatically
    labelling a source true, so the states describe how far review has got and
    what it found, never that the content is fact.
    """

    UNVERIFIED = "unverified"
    IN_REVIEW = "in_review"
    VERIFIED = "verified"
    DISPUTED = "disputed"
    REJECTED = "rejected"


class SourceReliability(str, Enum):
    """How much weight a source's track record earns it.

    A stated classification with a written rationale, rather than the numeric
    score it replaces, which had no defined methodology.
    """

    UNKNOWN = "unknown"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class GeographyLevel(str, Enum):
    """Tiers of the administrative hierarchy."""

    COUNTRY = "country"
    REGION = "region"
    STATE = "state"
    LGA = "lga"
    WARD = "ward"
    COMMUNITY = "community"


# Coarsest first. A node's parent must sit strictly above it here, which
# prevents inversions without forcing every country to use every tier: not
# every country has a region layer between country and state.
GEOGRAPHY_LEVEL_ORDER: tuple[GeographyLevel, ...] = (
    GeographyLevel.COUNTRY,
    GeographyLevel.REGION,
    GeographyLevel.STATE,
    GeographyLevel.LGA,
    GeographyLevel.WARD,
    GeographyLevel.COMMUNITY,
)


def geography_level_rank(level: GeographyLevel) -> int:
    """Position of a level in the hierarchy, coarsest first."""
    return GEOGRAPHY_LEVEL_ORDER.index(level)


# Backs the human-readable evidence reference. Declared on the metadata so
# Alembic creates it alongside the tables.
evidence_reference_seq = Sequence("evidence_reference_seq", metadata=Base.metadata)


# Association tables
user_organisation = Table(
    "user_organisation",
    Base.metadata,
    Column("user_id", UUID(as_uuid=True), ForeignKey("user.id"), primary_key=True),
    Column(
        "organisation_id",
        UUID(as_uuid=True),
        ForeignKey("organisation.id"),
        primary_key=True,
    ),
    Column(
        "role",
        SQLEnum(Role, values_callable=_enum_values),
        nullable=False,
        default=Role.PUBLIC_USER,
    ),
)

programme_thematic = Table(
    "programme_thematic",
    Base.metadata,
    Column("programme_id", UUID(as_uuid=True), ForeignKey("programme.id"), primary_key=True),
    Column(
        "thematic_id",
        UUID(as_uuid=True),
        ForeignKey("thematic_area.id"),
        primary_key=True,
    ),
)


class Organisation(TimestampedModel):
    """Organisation model."""

    __tablename__ = "organisation"

    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[Optional[str]] = mapped_column(Text)
    country: Mapped[str] = mapped_column(String(2), default="NG", nullable=False)
    timezone: Mapped[str] = mapped_column(String(50), default="Africa/Lagos", nullable=False)
    logo_url: Mapped[Optional[str]] = mapped_column(String(500))
    website: Mapped[Optional[str]] = mapped_column(String(500))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    users: Mapped[list["User"]] = relationship(
        secondary=user_organisation, back_populates="organisations"
    )
    programmes: Mapped[list["Programme"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    projects: Mapped[list["Project"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    evidence_items: Mapped[list["Evidence"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    sources: Mapped[list["Source"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )
    stories: Mapped[list["Story"]] = relationship(
        back_populates="organisation", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_organisation_code", "code"),
        Index("idx_organisation_active", "is_active"),
    )


class User(TimestampedModel):
    """User model."""

    __tablename__ = "user"

    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # Platform-level administration, distinct from the SUPER_ADMIN role, which
    # confers full rights within one organisation only.
    is_superuser: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    last_login: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    phone: Mapped[Optional[str]] = mapped_column(String(20))
    avatar_url: Mapped[Optional[str]] = mapped_column(String(500))
    timezone: Mapped[Optional[str]] = mapped_column(String(50))
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    preferences: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisations: Mapped[list["Organisation"]] = relationship(
        secondary=user_organisation, back_populates="users"
    )

    __table_args__ = (
        Index("idx_user_email", "email"),
        Index("idx_user_active", "is_active"),
        # Directory lookup matches on any part of a name or address, which a
        # B-tree index cannot serve: ILIKE '%term%' has no usable prefix.
        Index(
            "idx_user_name_trgm",
            "email",
            "first_name",
            "last_name",
            postgresql_using="gin",
            postgresql_ops={
                "email": "gin_trgm_ops",
                "first_name": "gin_trgm_ops",
                "last_name": "gin_trgm_ops",
            },
        ),
    )


class Geography(TimestampedModel):
    """A node in the Country / Region / State / LGA / Ward / Community tree.

    Reference data shared across organisations rather than tenant-scoped: the
    administrative map of a country is the same for every organisation working
    in it, and duplicating it per tenant would make comparison across tenants
    impossible.
    """

    # Not "geography": PostGIS defines a type of that name, and a table would
    # collide with it. Do not rename this to match the class.
    __tablename__ = "geographic_area"

    parent_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id", ondelete="RESTRICT"), nullable=True
    )
    level: Mapped[GeographyLevel] = mapped_column(
        SQLEnum(GeographyLevel, values_callable=_enum_values), nullable=False
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    # Administrative code where one exists, such as an ISO country code or a
    # national statistics office identifier.
    code: Mapped[Optional[str]] = mapped_column(String(32))
    centroid: Mapped[Optional[Any]] = mapped_column(Geometry("POINT", srid=4326), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    parent: Mapped[Optional["Geography"]] = relationship(
        remote_side="Geography.id", back_populates="children"
    )
    children: Mapped[list["Geography"]] = relationship(back_populates="parent")
    projects: Mapped[list["Project"]] = relationship(back_populates="geography")
    locations: Mapped[list["Location"]] = relationship(back_populates="geography")

    __table_args__ = (
        UniqueConstraint("parent_id", "level", "name", name="uq_geography_parent_level_name"),
        # Postgres treats NULLs as distinct, so the constraint above does not
        # cover root nodes. This closes that gap for countries.
        Index(
            "uq_geographic_area_root_level_name",
            "level",
            "name",
            unique=True,
            postgresql_where=text("parent_id IS NULL"),
        ),
        Index("idx_geographic_area_parent_id", "parent_id"),
        Index("idx_geographic_area_level", "level"),
        Index(
            "idx_geographic_area_name_trgm",
            "name",
            postgresql_using="gin",
            postgresql_ops={"name": "gin_trgm_ops"},
        ),
    )


class ThematicArea(TimestampedModel):
    """Thematic stream configuration."""

    __tablename__ = "thematic_area"

    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    code: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    description: Mapped[Optional[str]] = mapped_column(Text)
    icon: Mapped[Optional[str]] = mapped_column(String(50))
    color: Mapped[Optional[str]] = mapped_column(String(7))
    order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    programmes: Mapped[list["Programme"]] = relationship(
        secondary=programme_thematic, back_populates="thematic_areas"
    )
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="thematic_area")

    __table_args__ = (
        Index("idx_thematic_code", "code"),
        Index("idx_thematic_active", "is_active"),
        Index(
            "idx_thematic_name_trgm",
            "name",
            postgresql_using="gin",
            postgresql_ops={"name": "gin_trgm_ops"},
        ),
    )


class Programme(TimestampedModel):
    """Programme model."""

    __tablename__ = "programme"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    code: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    start_date: Mapped[Optional[date]] = mapped_column(Date)
    end_date: Mapped[Optional[date]] = mapped_column(Date)
    budget: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 2))
    budget_currency: Mapped[Optional[str]] = mapped_column(String(3))
    status: Mapped[str] = mapped_column(String(50), default="active", nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="programmes")
    projects: Mapped[list["Project"]] = relationship(
        back_populates="programme", cascade="all, delete-orphan"
    )
    thematic_areas: Mapped[list["ThematicArea"]] = relationship(
        secondary=programme_thematic, back_populates="programmes"
    )

    __table_args__ = (
        UniqueConstraint("organisation_id", "code", name="uq_programme_org_code"),
        Index("idx_programme_org_id", "organisation_id"),
    )


class Project(TimestampedModel):
    """Project model."""

    __tablename__ = "project"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    code: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    programme_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("programme.id"), nullable=True
    )
    start_date: Mapped[Optional[date]] = mapped_column(Date)
    end_date: Mapped[Optional[date]] = mapped_column(Date)
    budget: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 2))
    budget_currency: Mapped[Optional[str]] = mapped_column(String(3))
    status: Mapped[ProjectStatus] = mapped_column(
        SQLEnum(ProjectStatus, values_callable=_enum_values),
        default=ProjectStatus.PROPOSED,
        nullable=False,
    )
    # Replaces the former location_state / location_lga / location_community
    # strings, which could not be filtered on reliably or rolled up.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    implementing_org: Mapped[Optional[str]] = mapped_column(String(255))
    funding_source: Mapped[Optional[str]] = mapped_column(String(255))
    sector: Mapped[Optional[str]] = mapped_column(String(100))
    target_beneficiaries: Mapped[Optional[int]] = mapped_column(Integer)
    actual_completion: Mapped[Optional[date]] = mapped_column(Date)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="projects")
    programme: Mapped[Optional["Programme"]] = relationship(back_populates="projects")
    geography: Mapped[Optional["Geography"]] = relationship(back_populates="projects")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="project")
    locations: Mapped[list["Location"]] = relationship(back_populates="project")
    milestones: Mapped[list["Milestone"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    indicators: Mapped[list["Indicator"]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("name", "A"), ("code", "A"), ("description", "B")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        UniqueConstraint("organisation_id", "code", name="uq_project_org_code"),
        Index("idx_project_org_id", "organisation_id"),
        Index("idx_project_programme_id", "programme_id"),
        Index("idx_project_geography_id", "geography_id"),
        Index("idx_project_status", "status"),
        Index("idx_project_search", "search_vector", postgresql_using="gin"),
    )


class Milestone(TimestampedModel):
    """A dated checkpoint within a project."""

    __tablename__ = "milestone"

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    due_date: Mapped[Optional[date]] = mapped_column(Date)
    completed_date: Mapped[Optional[date]] = mapped_column(Date)
    status: Mapped[MilestoneStatus] = mapped_column(
        SQLEnum(MilestoneStatus, values_callable=_enum_values),
        default=MilestoneStatus.PENDING,
        nullable=False,
    )
    sequence: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Relationships
    project: Mapped["Project"] = relationship(back_populates="milestones")

    __table_args__ = (
        Index("idx_milestone_project_id", "project_id"),
        Index("idx_milestone_status", "status"),
    )


class Indicator(TimestampedModel):
    """A measurable quantity a project is expected to move.

    Baseline, target and current value live here so that evidence can record a
    measurement against a named indicator rather than restating the definition
    on every record.
    """

    __tablename__ = "indicator"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id", ondelete="CASCADE"), nullable=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    unit: Mapped[Optional[str]] = mapped_column(String(50))
    baseline_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    baseline_date: Mapped[Optional[date]] = mapped_column(Date)
    target_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    target_date: Mapped[Optional[date]] = mapped_column(Date)
    current_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))
    current_value_date: Mapped[Optional[date]] = mapped_column(Date)

    # Relationships
    project: Mapped[Optional["Project"]] = relationship(back_populates="indicators")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="indicator")

    __table_args__ = (
        Index("idx_indicator_organisation_id", "organisation_id"),
        Index("idx_indicator_project_id", "project_id"),
    )


class Location(TimestampedModel):
    """Geographic location model."""

    __tablename__ = "location"

    # Nullable so a location can be recorded for evidence that is not tied to a
    # project.
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=True
    )
    # The administrative area this point falls within. A Location is a
    # specific place; a Geography is the area it sits inside.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    latitude: Mapped[Optional[Decimal]] = mapped_column(Numeric(9, 6))
    longitude: Mapped[Optional[Decimal]] = mapped_column(Numeric(9, 6))
    geom: Mapped[Optional[Any]] = mapped_column(Geometry("POINT", srid=4326), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text)

    # Relationships
    project: Mapped[Optional["Project"]] = relationship(back_populates="locations")
    geography: Mapped[Optional["Geography"]] = relationship(back_populates="locations")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="location")

    __table_args__ = (
        Index("idx_location_project_id", "project_id"),
        Index("idx_location_geography_id", "geography_id"),
    )


class Source(TimestampedModel):
    """Source registry model."""

    __tablename__ = "source"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    source_type: Mapped[SourceType] = mapped_column(
        SQLEnum(SourceType, values_callable=_enum_values), nullable=False
    )
    url: Mapped[Optional[str]] = mapped_column(String(500))
    description: Mapped[Optional[str]] = mapped_column(Text)

    # Who published it, as distinct from the tenant that recorded it.
    publisher: Mapped[Optional[str]] = mapped_column(String(255))
    author: Mapped[Optional[str]] = mapped_column(String(255))
    publication_date: Mapped[Optional[date]] = mapped_column(Date)

    # Provenance
    document_url: Mapped[Optional[str]] = mapped_column(String(500))
    # Hash of the stored document, so a later copy can be shown to be the same
    # artefact that was reviewed.
    document_hash: Mapped[Optional[str]] = mapped_column(String(128))
    provenance: Mapped[Optional[str]] = mapped_column(Text)

    # Governance. There is deliberately no boolean "verified" and no numeric
    # credibility score: spec section 11 requires transparent states rather
    # than a source being labelled true, and section 7 rules out unexplained
    # scores.
    verification_state: Mapped[VerificationState] = mapped_column(
        SQLEnum(VerificationState, values_callable=_enum_values),
        default=VerificationState.UNVERIFIED,
        nullable=False,
    )
    reliability: Mapped[SourceReliability] = mapped_column(
        SQLEnum(SourceReliability, values_callable=_enum_values),
        default=SourceReliability.UNKNOWN,
        nullable=False,
    )
    reliability_rationale: Mapped[Optional[str]] = mapped_column(Text)
    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    review_date: Mapped[Optional[date]] = mapped_column(Date)
    # When this assessment should be revisited. A source verified years ago is
    # not thereby still verified.
    next_review_date: Mapped[Optional[date]] = mapped_column(Date)

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="sources")
    evidence_items: Mapped[list["Evidence"]] = relationship(back_populates="source")

    __table_args__ = (
        Index("idx_source_organisation_id", "organisation_id"),
        Index("idx_source_type", "source_type"),
        Index("idx_source_verification_state", "verification_state"),
    )


class Evidence(TimestampedModel):
    """Evidence registry model."""

    __tablename__ = "evidence"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=True
    )
    location_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.id"), nullable=True
    )
    source_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("source.id"), nullable=False
    )
    thematic_area_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("thematic_area.id"), nullable=True
    )
    # Evidence can be placed on the map without belonging to a project site.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    indicator_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("indicator.id"), nullable=True
    )
    # The field mission this record was gathered on, where it was gathered on
    # one. Provenance: it says the record came from people who went and looked.
    field_mission_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("field_mission.id"), nullable=True
    )
    # Supplied by the capturing client, unique per organisation. A field device
    # on a bad connection retries, and without this a retry would file the same
    # observation twice. See api/missions.py; spec section 17's offline toolkit
    # is not built, but a capture endpoint that duplicates on retry could not
    # be built on later.
    capture_key: Mapped[Optional[str]] = mapped_column(String(128))

    # Permanent, human-readable identifier. Generated by the database so it is
    # assigned exactly once, at insert, and cannot drift: an evidence record
    # must stay citable by the same reference for its whole life.
    reference: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        unique=True,
        server_default=text(
            "'EV-' || to_char(now(), 'YYYY') || '-' "
            "|| lpad(nextval('evidence_reference_seq')::text, 6, '0')"
        ),
    )

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[EvidenceStatus] = mapped_column(
        SQLEnum(EvidenceStatus, values_callable=_enum_values),
        default=EvidenceStatus.DRAFT,
        nullable=False,
    )
    evidence_date: Mapped[Optional[date]] = mapped_column(Date)

    # Evidence details
    beneficiaries: Mapped[Optional[int]] = mapped_column(Integer)
    outcome: Mapped[Optional[str]] = mapped_column(Text)
    confidence_level: Mapped[Optional[int]] = mapped_column(Integer)
    # The measurement this record contributes, against indicator_id. The
    # indicator holds the definition, baseline and target; evidence holds an
    # observation of it at a point in time.
    measured_value: Mapped[Optional[Decimal]] = mapped_column(Numeric(18, 4))

    # Files and media
    document_url: Mapped[Optional[str]] = mapped_column(String(500))
    image_urls: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)
    video_urls: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)

    # Verification
    verification_status: Mapped[str] = mapped_column(
        String(50), default="unverified", nullable=False
    )
    verified_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    verified_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    verifier_notes: Mapped[Optional[str]] = mapped_column(Text)

    # Approval
    approval_status: Mapped[str] = mapped_column(String(50), default="pending", nullable=False)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    # Metadata
    metadata_json: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)
    tags: Mapped[list[str]] = mapped_column(ARRAY(String), default=list, nullable=False)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="evidence_items")
    project: Mapped[Optional["Project"]] = relationship(back_populates="evidence_items")
    location: Mapped[Optional["Location"]] = relationship(back_populates="evidence_items")
    source: Mapped["Source"] = relationship(back_populates="evidence_items")
    geography: Mapped[Optional["Geography"]] = relationship()
    indicator: Mapped[Optional["Indicator"]] = relationship(back_populates="evidence_items")
    thematic_area: Mapped[Optional["ThematicArea"]] = relationship(back_populates="evidence_items")
    stories: Mapped[list["Story"]] = relationship(back_populates="evidence")
    audit_logs: Mapped[list["AuditLog"]] = relationship(back_populates="evidence")

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(
            ("reference", "A"),
            ("title", "A"),
            ("description", "B"),
            ("outcome", "C"),
        ),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_evidence_organisation_id", "organisation_id"),
        Index("idx_evidence_status", "status"),
        Index("idx_evidence_project_id", "project_id"),
        Index("idx_evidence_field_mission_id", "field_mission_id"),
        # Partial, because most evidence is not captured in the field and a
        # null capture_key must not collide with another null. This is what
        # actually makes a retried capture idempotent: the constraint refuses
        # the duplicate rather than the application racing to check first.
        Index(
            "uq_evidence_capture_key",
            "organisation_id",
            "capture_key",
            unique=True,
            postgresql_where=text("capture_key IS NOT NULL"),
        ),
        Index("idx_evidence_search", "search_vector", postgresql_using="gin"),
    )


class Story(TimestampedModel):
    """Public information story model."""

    __tablename__ = "story"

    # Tenancy is carried explicitly rather than inferred through evidence, so
    # story queries can be scoped without a join.
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    evidence_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence.id"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    headline: Mapped[Optional[str]] = mapped_column(String(500))
    body: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text)
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    status: Mapped[StoryStatus] = mapped_column(
        SQLEnum(StoryStatus, values_callable=_enum_values),
        default=StoryStatus.DRAFT,
        nullable=False,
    )
    featured: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    published_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Relationships
    organisation: Mapped["Organisation"] = relationship(back_populates="stories")
    evidence: Mapped["Evidence"] = relationship(back_populates="stories")

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(
            ("title", "A"),
            ("headline", "A"),
            ("summary", "B"),
            ("body", "C"),
        ),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_story_evidence_id", "evidence_id"),
        Index("idx_story_organisation_id", "organisation_id"),
        Index("idx_story_status", "status"),
        Index("idx_story_search", "search_vector", postgresql_using="gin"),
    )


class Question(TimestampedModel):
    """Citizen question model."""

    __tablename__ = "question"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    category: Mapped[Optional[str]] = mapped_column(String(100))
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    # Free text as the submitter typed it. geography_id is the resolved area,
    # set during triage; keeping both preserves what was actually said.
    location_state: Mapped[Optional[str]] = mapped_column(String(50))
    location_lga: Mapped[Optional[str]] = mapped_column(String(100))
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    is_anonymous: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    submitter_email: Mapped[Optional[str]] = mapped_column(String(255))
    status: Mapped[QuestionStatus] = mapped_column(
        SQLEnum(QuestionStatus, values_callable=_enum_values),
        default=QuestionStatus.NEW,
        nullable=False,
    )
    assigned_to: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    response: Mapped[Optional[str]] = mapped_column(Text)
    # Recorded separately from updated_by so approval can require a different
    # person from whoever drafted the response.
    responded_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    response_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    is_published: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # The body answering the question, once it has been triaged to one.
    organisation: Mapped[Optional["Organisation"]] = relationship()

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("question_text", "A"), ("response", "B"), ("category", "C")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_question_status", "status"),
        Index("idx_question_organisation_id", "organisation_id"),
        Index("idx_question_search", "search_vector", postgresql_using="gin"),
    )


class IntegritySignal(TimestampedModel):
    """A claim circulating in public, and what was found out about it.

    Spec sections 25-26. The record is about **information**, and the columns
    are chosen so that it cannot quietly become about people. There is no
    column for who spread a claim, no account handle, no audience segment and
    no demographic breakdown — section 4 forbids profiling citizens, and the
    surest way to honour that is to leave nowhere to put it. ``source`` and
    ``circulation`` describe a channel ("a voice note forwarded on WhatsApp in
    Bida", "a headline in a state daily"), not a person.

    ``finding`` is the conclusion; ``assessment`` is the reasoning behind it.
    They are separate columns because a verdict with no reasoning is exactly
    the kind of unexplainable intelligence section 4 rules out, and the API
    refuses to record one without the other.
    """

    __tablename__ = "integrity_signal"

    # Non-null, unlike a citizen question: a signal is logged by a member of
    # staff who already belongs to a body, so there is never a moment where it
    # belongs to nobody.
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    claim: Mapped[str] = mapped_column(Text, nullable=False)
    # Where it was seen, as a channel. See the class docstring.
    source: Mapped[Optional[str]] = mapped_column(String(255))
    circulation: Mapped[Optional[str]] = mapped_column(Text)
    first_observed: Mapped[Optional[date]] = mapped_column(Date)
    language: Mapped[str] = mapped_column(String(5), default="en", nullable=False)
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    thematic_area_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("thematic_area.id"), nullable=True
    )
    priority: Mapped[IntegritySignalPriority] = mapped_column(
        SQLEnum(IntegritySignalPriority, values_callable=_enum_values),
        default=IntegritySignalPriority.LOW_RISK,
        nullable=False,
    )
    status: Mapped[IntegritySignalStatus] = mapped_column(
        SQLEnum(IntegritySignalStatus, values_callable=_enum_values),
        default=IntegritySignalStatus.NEW,
        nullable=False,
    )
    assigned_to: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    finding: Mapped[Optional[IntegrityFinding]] = mapped_column(
        SQLEnum(IntegrityFinding, values_callable=_enum_values), nullable=True
    )
    assessment: Mapped[Optional[str]] = mapped_column(Text)
    impact: Mapped[Optional[str]] = mapped_column(Text)
    # The evidence the finding rests on. Optional on the record because an
    # assessment is drafted before it is cited; the API requires it before a
    # determination can be approved.
    evidence_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence.id"), nullable=True
    )
    # Recorded separately from updated_by so approval can require a different
    # person from whoever wrote the assessment.
    assessed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    assessed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    response: Mapped[Optional[str]] = mapped_column(Text)
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    organisation: Mapped["Organisation"] = relationship()
    evidence: Mapped[Optional["Evidence"]] = relationship()

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(
            ("claim", "A"),
            ("assessment", "B"),
            ("response", "B"),
            ("circulation", "C"),
        ),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_integrity_priority", "priority"),
        Index("idx_integrity_status", "status"),
        Index("idx_integrity_organisation_id", "organisation_id"),
        Index("idx_integrity_geography_id", "geography_id"),
        Index("idx_integrity_search", "search_vector", postgresql_using="gin"),
    )


class Scenario(TimestampedModel):
    """Something the organisation must be ready for, and how ready it is.

    Spec sections 28-31. The column that matters is ``status``, because it is
    the one an outsider reads as a claim: "we are ready for this".

    It is therefore **declared, not simply set**. Every declaration carries a
    rationale and the person who made it, and it is checked against a floor
    computed from what the record actually shows — whether a playbook exists,
    whether it has ever been rehearsed, whether the rehearsal is overdue, and
    whether anything critical found in it is still open. An owner may declare a
    status worse than the floor, because they may know something the system
    does not. They may not declare one better. See services/readiness.py.

    ``last_drill_date`` was the whole of the previous design: a date, with no
    record of what the drill found. A rehearsal whose findings are not written
    down is indistinguishable from one that never happened, so the date is now
    derived from completed Drill records rather than typed in.
    """

    __tablename__ = "scenario"

    # Non-null: readiness is something a particular body is accountable for,
    # and an ownerless scenario is a colour nobody answers for.
    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[Optional[str]] = mapped_column(String(50))
    description: Mapped[Optional[str]] = mapped_column(Text)
    trigger: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[ReadinessStatus] = mapped_column(
        SQLEnum(ReadinessStatus, values_callable=_enum_values),
        # A scenario with nothing behind it yet starts at the worst honest
        # answer, not the most flattering one. Declaring GREEN is an act
        # somebody performs and signs; it is not where a record begins.
        default=ReadinessStatus.RED,
        nullable=False,
    )
    # Why the current status was declared, and by whom. Required on every
    # declaration: a readiness colour with no stated reason is a number on a
    # dashboard that nobody can be held to.
    status_rationale: Mapped[Optional[str]] = mapped_column(Text)
    status_declared_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    status_declared_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    owner: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    # An external plan document may exist alongside the steps below; it is not
    # a substitute for them, because a URL cannot be checked for whether it
    # says who does what.
    playbook_url: Mapped[Optional[str]] = mapped_column(String(500))
    # How often this scenario must be rehearsed for its drill to count as
    # current. Null means no cadence has been set, which is itself a gap.
    drill_interval_days: Mapped[Optional[int]] = mapped_column(Integer)
    last_drill_date: Mapped[Optional[date]] = mapped_column(Date)

    organisation: Mapped[Optional["Organisation"]] = relationship()
    playbook_steps: Mapped[List["PlaybookStep"]] = relationship(
        back_populates="scenario",
        cascade="all, delete-orphan",
        order_by="PlaybookStep.position",
    )
    drills: Mapped[List["Drill"]] = relationship(
        back_populates="scenario",
        cascade="all, delete-orphan",
        order_by="Drill.scheduled_for",
    )

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("name", "A"), ("description", "B"), ("trigger", "C")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_scenario_status", "status"),
        Index("idx_scenario_organisation_id", "organisation_id"),
        Index("idx_scenario_search", "search_vector", postgresql_using="gin"),
    )


class FieldMission(TimestampedModel):
    """A planned trip to gather evidence in the field (spec section 18).

    This table is the one place in EPIRO that records where named members of
    staff will be, and when. That is a duty-of-care necessity and also, if
    built carelessly, a movement log for the people who do the most exposed
    work on the platform. Two decisions hold the line.

    **Location is recorded at mission level, not per person.** The mission
    names the area it covers and the window it runs in, because a coordinator
    has to know where to send help. There is no per-person position on this
    table and none on the check-in table either.

    **A check-in is a state, not a position.** "Safe", "delayed", "assistance
    required" is what a coordinator needs. A stream of coordinates would be a
    continuous track of an individual's movements, which is not necessary for
    the operational purpose and so, under spec section 20, is not collected.
    The prohibition there is written about citizens; the same reasoning
    applies to staff, who did not stop being people by being employed.

    There is also no column listing the citizens a mission spoke to. Where
    somebody's account becomes evidence, it goes through the source registry,
    which has its own rules about consent and attribution.
    """

    __tablename__ = "field_mission"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    purpose: Mapped[str] = mapped_column(Text, nullable=False)
    # Where the team is going, as an area. Not a coordinate per person.
    geography_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("geographic_area.id"), nullable=True
    )
    project_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=True
    )
    thematic_area_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("thematic_area.id"), nullable=True
    )
    planned_start: Mapped[date] = mapped_column(Date, nullable=False)
    planned_end: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[MissionStatus] = mapped_column(
        SQLEnum(MissionStatus, values_callable=_enum_values),
        default=MissionStatus.PLANNED,
        nullable=False,
    )
    lead_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    # What could go wrong and what is being done about it. A mission cannot be
    # approved without one: sending people somewhere without having written
    # down the risk is the failure this column exists to make impossible.
    risk_assessment: Mapped[Optional[str]] = mapped_column(Text)
    # Recorded separately from updated_by so approval can require a different
    # person from whoever planned the mission.
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    report: Mapped[Optional[str]] = mapped_column(Text)
    cancellation_reason: Mapped[Optional[str]] = mapped_column(Text)
    # How long the team may go without reporting in before a coordinator
    # should be worried. Whether a mission is overdue is derived from this and
    # the last check-in rather than stored, so the flag cannot go stale.
    check_in_interval_hours: Mapped[Optional[int]] = mapped_column(Integer)

    organisation: Mapped["Organisation"] = relationship()
    members: Mapped[List["MissionMember"]] = relationship(
        back_populates="mission", cascade="all, delete-orphan"
    )
    check_ins: Mapped[List["MissionCheckIn"]] = relationship(
        back_populates="mission",
        cascade="all, delete-orphan",
        order_by="MissionCheckIn.reported_at",
    )

    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        _search_vector(("title", "A"), ("purpose", "B"), ("report", "C")),
        nullable=True,
        deferred=True,
    )

    __table_args__ = (
        Index("idx_field_mission_organisation_id", "organisation_id"),
        Index("idx_field_mission_status", "status"),
        Index("idx_field_mission_geography_id", "geography_id"),
        Index("idx_field_mission_search", "search_vector", postgresql_using="gin"),
    )


class MissionMember(TimestampedModel):
    """Somebody who is going on a field mission.

    Carries no position and no per-person schedule: the mission already says
    where the team is going and when. This table answers "who is out there",
    which a coordinator needs in order to account for everyone.
    """

    __tablename__ = "mission_member"

    mission_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("field_mission.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=False
    )
    # What they are doing on this trip, in the team's own words.
    role_on_mission: Mapped[Optional[str]] = mapped_column(String(100))

    mission: Mapped["FieldMission"] = relationship(back_populates="members")

    __table_args__ = (
        UniqueConstraint("mission_id", "user_id", name="uq_mission_member"),
        Index("idx_mission_member_mission_id", "mission_id"),
    )


class MissionCheckIn(TimestampedModel):
    """A team reporting that it is all right, or that it is not.

    **There is no latitude or longitude here, and that is the point.** A
    coordinator needs to know whether a team is safe and whether anyone needs
    help. A stream of positions would additionally produce a continuous record
    of where individual members of staff went, which the operational purpose
    does not require. Spec section 20 limits collection to what is necessary;
    a note field lets a team say where they are when they choose to.
    """

    __tablename__ = "mission_check_in"

    mission_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("field_mission.id", ondelete="CASCADE"), nullable=False
    )
    state: Mapped[SafetyState] = mapped_column(
        SQLEnum(SafetyState, values_callable=_enum_values),
        default=SafetyState.SAFE,
        nullable=False,
    )
    reported_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    reported_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    note: Mapped[Optional[str]] = mapped_column(Text)

    mission: Mapped["FieldMission"] = relationship(back_populates="check_ins")

    __table_args__ = (
        Index("idx_mission_check_in_mission_id", "mission_id"),
        Index("idx_mission_check_in_state", "state"),
    )


class PlaybookStep(TimestampedModel):
    """One step of the plan for responding to a scenario.

    A plan that does not say who acts is not a plan, so ``responsible_role`` is
    required. ``within_hours`` is what makes a drill checkable: without a
    stated expectation there is nothing for a rehearsal to find wanting.
    """

    __tablename__ = "playbook_step"

    scenario_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scenario.id", ondelete="CASCADE"), nullable=False
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    responsible_role: Mapped[Role] = mapped_column(
        SQLEnum(Role, values_callable=_enum_values), nullable=False
    )
    within_hours: Mapped[Optional[int]] = mapped_column(Integer)

    scenario: Mapped["Scenario"] = relationship(back_populates="playbook_steps")

    __table_args__ = (
        UniqueConstraint("scenario_id", "position", name="uq_playbook_step_position"),
        Index("idx_playbook_step_scenario_id", "scenario_id"),
    )


class Drill(TimestampedModel):
    """A rehearsal of a scenario, and what it found.

    Scheduling one is a commitment; completing one requires a summary, because
    the point of the record is what was learned rather than that a date passed.
    """

    __tablename__ = "drill"

    scenario_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scenario.id", ondelete="CASCADE"), nullable=False
    )
    scheduled_for: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[DrillStatus] = mapped_column(
        SQLEnum(DrillStatus, values_callable=_enum_values),
        default=DrillStatus.SCHEDULED,
        nullable=False,
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    conducted_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    summary: Mapped[Optional[str]] = mapped_column(Text)
    # Why a rehearsal did not happen. Required on cancellation, so that a
    # scenario's drill history shows the gaps as well as the exercises.
    cancellation_reason: Mapped[Optional[str]] = mapped_column(Text)

    scenario: Mapped["Scenario"] = relationship(back_populates="drills")
    findings: Mapped[List["DrillFinding"]] = relationship(
        back_populates="drill",
        cascade="all, delete-orphan",
        order_by="DrillFinding.created_at",
    )

    __table_args__ = (
        Index("idx_drill_scenario_id", "scenario_id"),
        Index("idx_drill_status", "status"),
    )


class DrillFinding(TimestampedModel):
    """Something a rehearsal showed to be wrong.

    Resolution is recorded by a different person from the one who raised it.
    "I found a problem in my own drill and I say I have fixed it" is exactly
    the self-certification the rest of the platform refuses, and a critical
    finding holds readiness down until somebody else confirms it is closed.
    """

    __tablename__ = "drill_finding"

    drill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("drill.id", ondelete="CASCADE"), nullable=False
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[FindingSeverity] = mapped_column(
        SQLEnum(FindingSeverity, values_callable=_enum_values),
        default=FindingSeverity.OBSERVATION,
        nullable=False,
    )
    raised_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    resolved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    resolution: Mapped[Optional[str]] = mapped_column(Text)

    drill: Mapped["Drill"] = relationship(back_populates="findings")

    __table_args__ = (
        Index("idx_drill_finding_drill_id", "drill_id"),
        Index("idx_drill_finding_severity", "severity"),
    )


class WorkflowDefinition(TimestampedModel):
    """An organisation's review sequence for one kind of content.

    Spec section 36 asks for configurable workflows, giving the example
    Draft → Review → Fact Check → Compliance → Approval → Publication. Every
    configurable step in that list sits between submission and approval; draft
    and publication are the fixed ends of it.

    So what an organisation defines here is the sequence of review stages a
    record must clear before it counts as approved. The coarse lifecycle —
    draft, approved, published, withdrawn — stays fixed in code, deliberately:
    if the public portal's "published" filter read a configurable pointer, an
    organisation could change what published means to the public by editing
    its own workflow. Configurability must not reach the guarantees the
    platform makes to people outside it.
    """

    __tablename__ = "workflow_definition"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    # Which kind of content this governs: evidence, story or question. The
    # same strings the approval trail is addressed by.
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    stages: Mapped[list["WorkflowStage"]] = relationship(
        back_populates="definition",
        cascade="all, delete-orphan",
        order_by="WorkflowStage.position",
    )

    __table_args__ = (
        # One active definition per organisation and content type. Two would
        # make "which workflow applies" ambiguous, and the answer must never
        # be ambiguous for an approval.
        Index(
            "uq_workflow_active_per_type",
            "organisation_id",
            "entity_type",
            unique=True,
            postgresql_where=text("is_active"),
        ),
        Index("idx_workflow_organisation_id", "organisation_id"),
    )


class WorkflowStage(TimestampedModel):
    """One review step a record must clear."""

    __tablename__ = "workflow_stage"

    definition_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workflow_definition.id"), nullable=False
    )
    # Order within the definition, ascending. A record clears stages in this
    # order and is approved once the last one is cleared.
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    # Roles that may clear this stage, stored as role values.
    required_roles: Mapped[list[str]] = mapped_column(ARRAY(String), nullable=False)
    # Whether whoever clears this stage must differ from whoever cleared the
    # previous one. The platform forces this on the final stage regardless of
    # what is configured; see app/services/workflow.py.
    requires_distinct_actor: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    definition: Mapped["WorkflowDefinition"] = relationship(back_populates="stages")

    __table_args__ = (
        UniqueConstraint("definition_id", "position", name="uq_stage_position"),
        Index("idx_stage_definition_id", "definition_id"),
    )


class ApprovalRecord(TimestampedModel):
    """One approval decision, kept whatever the outcome.

    Spec section 36 requires approvals to store the reviewer, timestamp,
    decision, comments and version. Holding only the latest approver on the
    record itself loses every rejection and every earlier round, which is
    exactly the history a reviewer needs.

    Addressed by entity_type and entity_id rather than a foreign key per kind,
    so evidence, stories and questions share one trail.
    """

    __tablename__ = "approval_record"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    # The version the decision was made against, so a later edit does not make
    # the decision look like it covered content it never saw.
    entity_version: Mapped[Optional[int]] = mapped_column(Integer)

    decision: Mapped[ApprovalDecision] = mapped_column(
        SQLEnum(ApprovalDecision, values_callable=_enum_values), nullable=False
    )
    # Which configured stage this decision cleared, when the organisation has
    # defined a workflow. Null means the single implicit stage every
    # organisation has before it configures anything.
    #
    # How far a record has got is derived from these records rather than kept
    # as a pointer on the record itself: a pointer is a second copy of the
    # truth, and the one that drifts is always the copy.
    workflow_stage_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workflow_stage.id"), nullable=True
    )
    reviewer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=False
    )
    decided_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    comments: Mapped[Optional[str]] = mapped_column(Text)

    __table_args__ = (
        Index("idx_approval_entity", "entity_type", "entity_id"),
        Index("idx_approval_organisation_id", "organisation_id"),
        Index("idx_approval_reviewer_id", "reviewer_id"),
    )


class AuditLog(TimestampedModel):
    """Audit logging model."""

    __tablename__ = "audit_log"

    organisation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("organisation.id"), nullable=True
    )
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    evidence_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("evidence.id"), nullable=True
    )
    action: Mapped[str] = mapped_column(String(255), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True))
    old_values: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB)
    new_values: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45))
    user_agent: Mapped[Optional[str]] = mapped_column(String(500))

    # Relationships
    evidence: Mapped[Optional["Evidence"]] = relationship(back_populates="audit_logs")

    __table_args__ = (
        Index("idx_audit_organisation_id", "organisation_id"),
        Index("idx_audit_user_id", "user_id"),
        Index("idx_audit_action", "action"),
    )
