"""Baseline schema.

Replaces the previous 001_initial_schema, which created only 2 of the 15
tables and named a column "metadata" that the models call "metadata_json".
Because the application also called create_all() at startup, deployed
databases may hold either shape. There is no in-place upgrade path between
them: an existing environment should be re-provisioned from this baseline, or
inspected and stamped once confirmed to match.

Revision ID: 11b92c867aa6
Revises: 
Create Date: 2026-09-17 07:41:22.715170

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11b92c867aa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostGIS backs the location.geom column, so the extension must exist
    # before the spatial table is created. Creating it here rather than only
    # in init.sql means a database provisioned by migration alone also works.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_organisation_active', 'organisation', ['is_active'], unique=False)
    op.create_index('idx_organisation_code', 'organisation', ['code'], unique=False)
    op.create_table('thematic_area',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_thematic_active', 'thematic_area', ['is_active'], unique=False)
    op.create_index('idx_thematic_code', 'thematic_area', ['code'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_active', 'user', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.create_table('integrity_signal',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('low_risk', 'emerging', 'material', 'crisis', 'national', name='integritysignalpriority'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integrity_priority', 'integrity_signal', ['priority'], unique=False)
    op.create_index('idx_integrity_status', 'integrity_signal', ['status'], unique=False)
    op.create_table('programme',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_programme_org_code')
    )
    op.create_index('idx_programme_org_id', 'programme', ['organisation_id'], unique=False)
    op.create_table('question',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('location_state', sa.String(length=50), nullable=True),
    sa.Column('location_lga', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'triaged', 'researching', 'verified', 'response_drafted', 'approved', 'published', 'closed', name='questionstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_organisation_id', 'question', ['organisation_id'], unique=False)
    op.create_index('idx_question_status', 'question', ['status'], unique=False)
    op.create_table('scenario',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('green', 'amber', 'red', 'black', name='readinessstatus'), nullable=False),
    sa.Column('owner', sa.UUID(), nullable=True),
    sa.Column('playbook_url', sa.String(length=500), nullable=True),
    sa.Column('last_drill_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scenario_status', 'scenario', ['status'], unique=False)
    op.create_table('source',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_organisation_id', 'source', ['organisation_id'], unique=False)
    op.create_index('idx_source_type', 'source', ['source_type'], unique=False)
    op.create_table('user_organisation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'executive', 'editor', 'evidence_manager', 'researcher', 'field_officer', 'verifier', 'integrity_analyst', 'content_manager', 'media_manager', 'translator', 'approver', 'analyst', 'public_user', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organisation_id')
    )
    op.create_table('programme_thematic',
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('thematic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.ForeignKeyConstraint(['thematic_id'], ['thematic_area.id'], ),
    sa.PrimaryKeyConstraint('programme_id', 'thematic_id')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location_state', sa.String(length=50), nullable=True),
    sa.Column('location_lga', sa.String(length=100), nullable=True),
    sa.Column('location_community', sa.String(length=100), nullable=True),
    sa.Column('implementing_org', sa.String(length=255), nullable=True),
    sa.Column('target_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_project_org_code')
    )
    op.create_index('idx_project_org_id', 'project', ['organisation_id'], unique=False)
    op.create_index('idx_project_programme_id', 'project', ['programme_id'], unique=False)
    op.create_geospatial_table('location',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('community', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_location_geom', 'location', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_location_project_id', 'location', ['project_id'], unique=False)
    op.create_index('idx_location_state', 'location', ['state'], unique=False)
    op.create_table('evidence',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('thematic_area_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'verified', 'approved', 'published', 'archived', 'rejected', name='evidencestatus'), nullable=False),
    sa.Column('evidence_date', sa.Date(), nullable=True),
    sa.Column('beneficiaries', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verifier_notes', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['thematic_area_id'], ['thematic_area.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_organisation_id', 'evidence', ['organisation_id'], unique=False)
    op.create_index('idx_evidence_project_id', 'evidence', ['project_id'], unique=False)
    op.create_index('idx_evidence_status', 'evidence', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_organisation_id', 'audit_log', ['organisation_id'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('story',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_story_evidence_id', 'story', ['evidence_id'], unique=False)
    op.create_index('idx_story_organisation_id', 'story', ['organisation_id'], unique=False)
    op.create_index('idx_story_status', 'story', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_status', table_name='story')
    op.drop_index('idx_story_organisation_id', table_name='story')
    op.drop_index('idx_story_evidence_id', table_name='story')
    op.drop_table('story')
    op.drop_index('idx_audit_user_id', table_name='audit_log')
    op.drop_index('idx_audit_organisation_id', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_evidence_status', table_name='evidence')
    op.drop_index('idx_evidence_project_id', table_name='evidence')
    op.drop_index('idx_evidence_organisation_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('idx_location_state', table_name='location')
    op.drop_index('idx_location_project_id', table_name='location')
    op.drop_geospatial_index('idx_location_geom', table_name='location', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('location')
    op.drop_index('idx_project_programme_id', table_name='project')
    op.drop_index('idx_project_org_id', table_name='project')
    op.drop_table('project')
    op.drop_table('programme_thematic')
    op.drop_table('user_organisation')
    op.drop_index('idx_source_type', table_name='source')
    op.drop_index('idx_source_organisation_id', table_name='source')
    op.drop_table('source')
    op.drop_index('idx_scenario_status', table_name='scenario')
    op.drop_table('scenario')
    op.drop_index('idx_question_status', table_name='question')
    op.drop_index('idx_question_organisation_id', table_name='question')
    op.drop_table('question')
    op.drop_index('idx_programme_org_id', table_name='programme')
    op.drop_table('programme')
    op.drop_index('idx_integrity_status', table_name='integrity_signal')
    op.drop_index('idx_integrity_priority', table_name='integrity_signal')
    op.drop_table('integrity_signal')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_user_active', table_name='user')
    op.drop_table('user')
    op.drop_index('idx_thematic_code', table_name='thematic_area')
    op.drop_index('idx_thematic_active', table_name='thematic_area')
    op.drop_table('thematic_area')
    op.drop_index('idx_organisation_code', table_name='organisation')
    op.drop_index('idx_organisation_active', table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###

    # Autogenerate drops the tables but leaves the native enum types behind,
    # which makes a subsequent upgrade fail with "type already exists".
    for enum_name in (
        "role",
        "evidencestatus",
        "questionstatus",
        "integritysignalpriority",
        "readinessstatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
