"""Add the action register: a decision traced back to what prompted it.

The last link in the chain the specification draws — evidence becomes a
signal, a signal is assessed into a finding, and that finding implies
something somebody has to own and answer for.

Revision ID: 139003d42832
Revises: 4dde921bc90f
Create Date: 2026-09-19 12:58:23.104338

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139003d42832'
down_revision: Union[str, None] = '4dde921bc90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('origin_type', sa.Enum('integrity_signal', 'drill_finding', 'scenario', 'evidence', name='actionorigin'), nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('thematic_area_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'in_progress', 'done', 'dropped', name='actionstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_action_created_by_id_user')),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_action_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_action_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_action_owner_id_user')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_action_scenario_id_scenario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thematic_area_id'], ['thematic_area.id'], name=op.f('fk_action_thematic_area_id_thematic_area')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action'))
    )
    op.create_index('idx_action_organisation_id', 'action', ['organisation_id'], unique=False)
    op.create_index('idx_action_origin', 'action', ['origin_type', 'origin_id'], unique=False)
    op.create_index('idx_action_owner_id', 'action', ['owner_id'], unique=False)
    op.create_index('idx_action_scenario_id', 'action', ['scenario_id'], unique=False)
    op.create_index('idx_action_status', 'action', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_action_status', table_name='action')
    op.drop_index('idx_action_scenario_id', table_name='action')
    op.drop_index('idx_action_owner_id', table_name='action')
    op.drop_index('idx_action_origin', table_name='action')
    op.drop_index('idx_action_organisation_id', table_name='action')
    op.drop_table('action')

    # Autogenerate does not drop the enum types it created, so a downgrade
    # followed by an upgrade fails on "type already exists". Dropped
    # explicitly, as every other migration in this history does.
    sa.Enum(name='actionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='actionorigin').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
