"""Add the approval trail.

Spec section 36 requires an approval to keep its reviewer, timestamp,
decision, comments and the version reviewed. The entity tables hold only the
latest approver, so a rejection or an earlier round left no record at all.

Addressed by (entity_type, entity_id) rather than a foreign key per kind, so
evidence, stories and questions share one trail.

Revision ID: 16f625feaee6
Revises: 264ed83a95a5
Create Date: 2026-09-17 12:49:19.561436

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f625feaee6'
down_revision: Union[str, None] = '264ed83a95a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_record',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_version', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'changes_requested', name='approvaldecision'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_approval_record_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('fk_approval_record_reviewer_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_record'))
    )
    op.create_index('idx_approval_entity', 'approval_record', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_approval_organisation_id', 'approval_record', ['organisation_id'], unique=False)
    op.create_index('idx_approval_reviewer_id', 'approval_record', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approval_reviewer_id', table_name='approval_record')
    op.drop_index('idx_approval_organisation_id', table_name='approval_record')
    op.drop_index('idx_approval_entity', table_name='approval_record')
    op.drop_table('approval_record')
    # ### end Alembic commands ###

    # Dropping the table leaves the native enum type behind, so a subsequent
    # upgrade would fail with "type approvaldecision already exists".
    op.execute("DROP TYPE IF EXISTS approvaldecision")
