"""Baseline schema.

One revision for the whole Phase 1 and Phase 2 schema. Safe to squash because
this branch has never been deployed, so no database holds an intermediate
shape.

Two things autogenerate cannot be trusted with here: it does not emit
sequences, and without the constraint naming convention on the metadata it
emits drop_constraint(None, ...) for Postgres-assigned names, which cannot
run. Both are handled explicitly.

The administrative hierarchy table is geographic_area, not geography: PostGIS
already defines a type called geography and a table of that name collides
with it.

Revision ID: 264ed83a95a5
Revises: 
Create Date: 2026-09-17 12:33:53.321574

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '264ed83a95a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostGIS backs geographic_area.centroid and location.geom, so the
    # extension must exist before those tables are created. Doing it here
    # means a database provisioned by migration alone works without init.sql.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # Backs the human-readable evidence reference. Alembic's autogenerate does
    # not emit sequences, so without this the evidence table's server_default
    # would reference a sequence that does not exist and every insert would
    # fail.
    op.execute("CREATE SEQUENCE IF NOT EXISTS evidence_reference_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('geographic_area',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('country', 'region', 'state', 'lga', 'ward', 'community', name='geographylevel'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['geographic_area.id'], name=op.f('fk_geographic_area_parent_id_geographic_area'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geographic_area')),
    sa.UniqueConstraint('parent_id', 'level', 'name', name='uq_geography_parent_level_name')
    )
    op.create_geospatial_index('idx_geographic_area_centroid', 'geographic_area', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_geographic_area_level', 'geographic_area', ['level'], unique=False)
    op.create_index('idx_geographic_area_parent_id', 'geographic_area', ['parent_id'], unique=False)
    op.create_index('uq_geographic_area_root_level_name', 'geographic_area', ['level', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('organisation',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation')),
    sa.UniqueConstraint('code', name=op.f('uq_organisation_code')),
    sa.UniqueConstraint('name', name=op.f('uq_organisation_name'))
    )
    op.create_index('idx_organisation_active', 'organisation', ['is_active'], unique=False)
    op.create_index('idx_organisation_code', 'organisation', ['code'], unique=False)
    op.create_table('thematic_area',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thematic_area')),
    sa.UniqueConstraint('code', name=op.f('uq_thematic_area_code')),
    sa.UniqueConstraint('name', name=op.f('uq_thematic_area_name'))
    )
    op.create_index('idx_thematic_active', 'thematic_area', ['is_active'], unique=False)
    op.create_index('idx_thematic_code', 'thematic_area', ['code'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_index('idx_user_active', 'user', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.create_table('integrity_signal',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('low_risk', 'emerging', 'material', 'crisis', 'national', name='integritysignalpriority'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_integrity_signal_approved_by_user')),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name=op.f('fk_integrity_signal_assigned_to_user')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_integrity_signal_organisation_id_organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrity_signal'))
    )
    op.create_index('idx_integrity_priority', 'integrity_signal', ['priority'], unique=False)
    op.create_index('idx_integrity_status', 'integrity_signal', ['status'], unique=False)
    op.create_table('programme',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_programme_organisation_id_organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme')),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_programme_org_code')
    )
    op.create_index('idx_programme_org_id', 'programme', ['organisation_id'], unique=False)
    op.create_table('question',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('location_state', sa.String(length=50), nullable=True),
    sa.Column('location_lga', sa.String(length=100), nullable=True),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('new', 'triaged', 'researching', 'verified', 'response_drafted', 'approved', 'published', 'closed', name='questionstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_question_approved_by_user')),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name=op.f('fk_question_assigned_to_user')),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_question_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_question_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['responded_by'], ['user.id'], name=op.f('fk_question_responded_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_index('idx_question_organisation_id', 'question', ['organisation_id'], unique=False)
    op.create_index('idx_question_status', 'question', ['status'], unique=False)
    op.create_table('scenario',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('green', 'amber', 'red', 'black', name='readinessstatus'), nullable=False),
    sa.Column('owner', sa.UUID(), nullable=True),
    sa.Column('playbook_url', sa.String(length=500), nullable=True),
    sa.Column('last_drill_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_scenario_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], name=op.f('fk_scenario_owner_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario'))
    )
    op.create_index('idx_scenario_status', 'scenario', ['status'], unique=False)
    op.create_table('source',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('official_document', 'government_data', 'research', 'field_report', 'interview', 'media_report', 'dataset', 'photograph', 'video', 'audio', 'user_submission', 'institutional_source', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('document_hash', sa.String(length=128), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('verification_state', sa.Enum('unverified', 'in_review', 'verified', 'disputed', 'rejected', name='verificationstate'), nullable=False),
    sa.Column('reliability', sa.Enum('unknown', 'low', 'moderate', 'high', name='sourcereliability'), nullable=False),
    sa.Column('reliability_rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_source_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_source_reviewed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_index('idx_source_organisation_id', 'source', ['organisation_id'], unique=False)
    op.create_index('idx_source_type', 'source', ['source_type'], unique=False)
    op.create_index('idx_source_verification_state', 'source', ['verification_state'], unique=False)
    op.create_table('user_organisation',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'executive', 'editor', 'evidence_manager', 'researcher', 'field_officer', 'verifier', 'integrity_analyst', 'content_manager', 'media_manager', 'translator', 'approver', 'analyst', 'public_user', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_user_organisation_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_organisation_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'organisation_id', name=op.f('pk_user_organisation'))
    )
    op.create_table('programme_thematic',
    sa.Column('programme_id', sa.UUID(), nullable=False),
    sa.Column('thematic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_programme_thematic_programme_id_programme')),
    sa.ForeignKeyConstraint(['thematic_id'], ['thematic_area.id'], name=op.f('fk_programme_thematic_thematic_id_thematic_area')),
    sa.PrimaryKeyConstraint('programme_id', 'thematic_id', name=op.f('pk_programme_thematic'))
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'planned', 'active', 'delayed', 'completed', 'suspended', 'archived', name='projectstatus'), nullable=False),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('implementing_org', sa.String(length=255), nullable=True),
    sa.Column('funding_source', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('target_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('actual_completion', sa.Date(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_project_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_project_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_project_programme_id_programme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_project_org_code')
    )
    op.create_index('idx_project_geography_id', 'project', ['geography_id'], unique=False)
    op.create_index('idx_project_org_id', 'project', ['organisation_id'], unique=False)
    op.create_index('idx_project_programme_id', 'project', ['programme_id'], unique=False)
    op.create_index('idx_project_status', 'project', ['status'], unique=False)
    op.create_table('indicator',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_value_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_indicator_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_indicator_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator'))
    )
    op.create_index('idx_indicator_organisation_id', 'indicator', ['organisation_id'], unique=False)
    op.create_index('idx_indicator_project_id', 'indicator', ['project_id'], unique=False)
    op.create_geospatial_table('location',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_location_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_location_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_index('idx_location_geography_id', 'location', ['geography_id'], unique=False)
    op.create_geospatial_index('idx_location_geom', 'location', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_location_project_id', 'location', ['project_id'], unique=False)
    op.create_table('milestone',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'missed', name='milestonestatus'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_milestone_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone'))
    )
    op.create_index('idx_milestone_project_id', 'milestone', ['project_id'], unique=False)
    op.create_index('idx_milestone_status', 'milestone', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('thematic_area_id', sa.UUID(), nullable=True),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('indicator_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=32), server_default=sa.text("'EV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('evidence_reference_seq')::text, 6, '0')"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'verified', 'approved', 'published', 'archived', 'rejected', name='evidencestatus'), nullable=False),
    sa.Column('evidence_date', sa.Date(), nullable=True),
    sa.Column('beneficiaries', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verifier_notes', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_evidence_approved_by_user')),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_evidence_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], name=op.f('fk_evidence_indicator_id_indicator')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_evidence_location_id_location')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_evidence_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_evidence_project_id_project')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_evidence_source_id_source')),
    sa.ForeignKeyConstraint(['thematic_area_id'], ['thematic_area.id'], name=op.f('fk_evidence_thematic_area_id_thematic_area')),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], name=op.f('fk_evidence_verified_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('reference', name=op.f('uq_evidence_reference'))
    )
    op.create_index('idx_evidence_organisation_id', 'evidence', ['organisation_id'], unique=False)
    op.create_index('idx_evidence_project_id', 'evidence', ['project_id'], unique=False)
    op.create_index('idx_evidence_status', 'evidence', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_audit_log_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_audit_log_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_organisation_id', 'audit_log', ['organisation_id'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_table('story',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_story_approved_by_user')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_story_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_story_organisation_id_organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story'))
    )
    op.create_index('idx_story_evidence_id', 'story', ['evidence_id'], unique=False)
    op.create_index('idx_story_organisation_id', 'story', ['organisation_id'], unique=False)
    op.create_index('idx_story_status', 'story', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_status', table_name='story')
    op.drop_index('idx_story_organisation_id', table_name='story')
    op.drop_index('idx_story_evidence_id', table_name='story')
    op.drop_table('story')
    op.drop_index('idx_audit_user_id', table_name='audit_log')
    op.drop_index('idx_audit_organisation_id', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_evidence_status', table_name='evidence')
    op.drop_index('idx_evidence_project_id', table_name='evidence')
    op.drop_index('idx_evidence_organisation_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('idx_milestone_status', table_name='milestone')
    op.drop_index('idx_milestone_project_id', table_name='milestone')
    op.drop_table('milestone')
    op.drop_index('idx_location_project_id', table_name='location')
    op.drop_geospatial_index('idx_location_geom', table_name='location', postgresql_using='gist', column_name='geom')
    op.drop_index('idx_location_geography_id', table_name='location')
    op.drop_geospatial_table('location')
    op.drop_index('idx_indicator_project_id', table_name='indicator')
    op.drop_index('idx_indicator_organisation_id', table_name='indicator')
    op.drop_table('indicator')
    op.drop_index('idx_project_status', table_name='project')
    op.drop_index('idx_project_programme_id', table_name='project')
    op.drop_index('idx_project_org_id', table_name='project')
    op.drop_index('idx_project_geography_id', table_name='project')
    op.drop_table('project')
    op.drop_table('programme_thematic')
    op.drop_table('user_organisation')
    op.drop_index('idx_source_verification_state', table_name='source')
    op.drop_index('idx_source_type', table_name='source')
    op.drop_index('idx_source_organisation_id', table_name='source')
    op.drop_table('source')
    op.drop_index('idx_scenario_status', table_name='scenario')
    op.drop_table('scenario')
    op.drop_index('idx_question_status', table_name='question')
    op.drop_index('idx_question_organisation_id', table_name='question')
    op.drop_table('question')
    op.drop_index('idx_programme_org_id', table_name='programme')
    op.drop_table('programme')
    op.drop_index('idx_integrity_status', table_name='integrity_signal')
    op.drop_index('idx_integrity_priority', table_name='integrity_signal')
    op.drop_table('integrity_signal')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_user_active', table_name='user')
    op.drop_table('user')
    op.drop_index('idx_thematic_code', table_name='thematic_area')
    op.drop_index('idx_thematic_active', table_name='thematic_area')
    op.drop_table('thematic_area')
    op.drop_index('idx_organisation_code', table_name='organisation')
    op.drop_index('idx_organisation_active', table_name='organisation')
    op.drop_table('organisation')
    op.drop_index('uq_geographic_area_root_level_name', table_name='geographic_area', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index('idx_geographic_area_parent_id', table_name='geographic_area')
    op.drop_index('idx_geographic_area_level', table_name='geographic_area')
    op.drop_geospatial_index('idx_geographic_area_centroid', table_name='geographic_area', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('geographic_area')
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS evidence_reference_seq")

    # Autogenerate drops the tables but leaves the native enum types behind,
    # which makes a subsequent upgrade fail with "type already exists".
    for enum_name in (
        "role",
        "evidencestatus",
        "questionstatus",
        "integritysignalpriority",
        "readinessstatus",
        "projectstatus",
        "milestonestatus",
        "geographylevel",
        "sourcetype",
        "verificationstate",
        "sourcereliability",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
