"""Add search vectors and their indexes.

Search was ``ILIKE '%term%'`` across four tables. A leading wildcard makes a
B-tree index unusable, so every search was a sequential scan of the whole
table. This adds a stored, generated tsvector per searchable table with a GIN
index over it, and pg_trgm indexes for the name and directory lookups that
legitimately stay as substring matches.

The vectors are generated columns rather than trigger-maintained, so a row
cannot end up with a vector that does not describe it.

Revision ID: 2f8ad0bf8ffa
Revises: 16f625feaee6
Create Date: 2026-09-17 12:59:13.421685

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f8ad0bf8ffa'
down_revision: Union[str, None] = '16f625feaee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # gin_trgm_ops comes from pg_trgm, so the extension must exist before any
    # index below references it. Autogenerate does not emit extensions.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("reference", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("title", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("description", \'\')), \'B\') || setweight(to_tsvector(\'english\', coalesce("outcome", \'\')), \'C\')', persisted=True), nullable=True))
    op.create_index('idx_evidence_search', 'evidence', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_geographic_area_name_trgm', 'geographic_area', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.add_column('project', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("name", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("code", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("description", \'\')), \'B\')', persisted=True), nullable=True))
    op.create_index('idx_project_search', 'project', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('question', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("question_text", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("response", \'\')), \'B\') || setweight(to_tsvector(\'english\', coalesce("category", \'\')), \'C\')', persisted=True), nullable=True))
    op.create_index('idx_question_search', 'question', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('scenario', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("name", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("description", \'\')), \'B\') || setweight(to_tsvector(\'english\', coalesce("trigger", \'\')), \'C\')', persisted=True), nullable=True))
    op.create_index('idx_scenario_search', 'scenario', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('story', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("title", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("headline", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("summary", \'\')), \'B\') || setweight(to_tsvector(\'english\', coalesce("body", \'\')), \'C\')', persisted=True), nullable=True))
    op.create_index('idx_story_search', 'story', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_thematic_name_trgm', 'thematic_area', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_user_name_trgm', 'user', ['email', 'first_name', 'last_name'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops', 'first_name': 'gin_trgm_ops', 'last_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_name_trgm', table_name='user', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops', 'first_name': 'gin_trgm_ops', 'last_name': 'gin_trgm_ops'})
    op.drop_index('idx_thematic_name_trgm', table_name='thematic_area', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_story_search', table_name='story', postgresql_using='gin')
    op.drop_column('story', 'search_vector')
    op.drop_index('idx_scenario_search', table_name='scenario', postgresql_using='gin')
    op.drop_column('scenario', 'search_vector')
    op.drop_index('idx_question_search', table_name='question', postgresql_using='gin')
    op.drop_column('question', 'search_vector')
    op.drop_index('idx_project_search', table_name='project', postgresql_using='gin')
    op.drop_column('project', 'search_vector')
    op.drop_index('idx_geographic_area_name_trgm', table_name='geographic_area', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_evidence_search', table_name='evidence', postgresql_using='gin')
    op.drop_column('evidence', 'search_vector')
    # ### end Alembic commands ###

    # pg_trgm is deliberately left in place, as postgis is: dropping an
    # extension on downgrade would break anything else in the database that
    # came to depend on it.
