"""field operations and missions

Spec section 18. Field missions, the team on them, their safety check-ins, and
the link from evidence back to the trip it was gathered on.

Two things to note about what is deliberately absent from these tables. There
is no position column on mission_check_in and none on mission_member: a
check-in records a state, not a coordinate, so the schema has nowhere to
accumulate a movement trail for an individual member of staff. And there is no
column listing the citizens a mission spoke to; where somebody's account
becomes evidence it goes through the source registry. See
docs/FIELD_OPERATIONS.md.

One hand-written adjustment: the downgrade drops the two enum types this
migration introduces. Autogenerate leaves them behind, so a down-then-up cycle
fails on the second CREATE TYPE. This is a known autogenerate gap, recorded in
docs/DOMAIN_MODEL.md.

``evidence.capture_key`` gets a **partial** unique index over
(organisation_id, capture_key) where the key is not null. That constraint is
what actually makes a retried field capture idempotent: the database refuses
the duplicate rather than the application racing to check for one first. Most
evidence is not captured in the field, and a null key must not collide with
another null, hence partial.

Revision ID: 4dde921bc90f
Revises: 72eb8f4f578f
Create Date: 2026-09-18 23:52:20.169844

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dde921bc90f'
down_revision: Union[str, None] = '72eb8f4f578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


MISSION_STATUS = sa.Enum(
    "planned", "approved", "in_progress", "completed", "cancelled", name="missionstatus"
)
SAFETY_STATE = sa.Enum("safe", "delayed", "assistance_required", name="safetystate")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_mission',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('geography_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('thematic_area_id', sa.UUID(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_end', sa.Date(), nullable=False),
    sa.Column('status', MISSION_STATUS, nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('check_in_interval_hours', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('setweight(to_tsvector(\'english\', coalesce("title", \'\')), \'A\') || setweight(to_tsvector(\'english\', coalesce("purpose", \'\')), \'B\') || setweight(to_tsvector(\'english\', coalesce("report", \'\')), \'C\')', persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('fk_field_mission_approved_by_user')),
    sa.ForeignKeyConstraint(['geography_id'], ['geographic_area.id'], name=op.f('fk_field_mission_geography_id_geographic_area')),
    sa.ForeignKeyConstraint(['lead_id'], ['user.id'], name=op.f('fk_field_mission_lead_id_user')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_field_mission_organisation_id_organisation')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_field_mission_project_id_project')),
    sa.ForeignKeyConstraint(['thematic_area_id'], ['thematic_area.id'], name=op.f('fk_field_mission_thematic_area_id_thematic_area')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_mission'))
    )
    op.create_index('idx_field_mission_geography_id', 'field_mission', ['geography_id'], unique=False)
    op.create_index('idx_field_mission_organisation_id', 'field_mission', ['organisation_id'], unique=False)
    op.create_index('idx_field_mission_search', 'field_mission', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_field_mission_status', 'field_mission', ['status'], unique=False)
    op.create_table('mission_check_in',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('state', SAFETY_STATE, nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['field_mission.id'], name=op.f('fk_mission_check_in_mission_id_field_mission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['user.id'], name=op.f('fk_mission_check_in_reported_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_check_in'))
    )
    op.create_index('idx_mission_check_in_mission_id', 'mission_check_in', ['mission_id'], unique=False)
    op.create_index('idx_mission_check_in_state', 'mission_check_in', ['state'], unique=False)
    op.create_table('mission_member',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_on_mission', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['field_mission.id'], name=op.f('fk_mission_member_mission_id_field_mission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mission_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_member')),
    sa.UniqueConstraint('mission_id', 'user_id', name='uq_mission_member')
    )
    op.create_index('idx_mission_member_mission_id', 'mission_member', ['mission_id'], unique=False)
    op.add_column('evidence', sa.Column('field_mission_id', sa.UUID(), nullable=True))
    op.add_column('evidence', sa.Column('capture_key', sa.String(length=128), nullable=True))
    op.create_index('idx_evidence_field_mission_id', 'evidence', ['field_mission_id'], unique=False)
    op.create_index('uq_evidence_capture_key', 'evidence', ['organisation_id', 'capture_key'], unique=True, postgresql_where=sa.text('capture_key IS NOT NULL'))
    op.create_foreign_key(op.f('fk_evidence_field_mission_id_field_mission'), 'evidence', 'field_mission', ['field_mission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_field_mission_id_field_mission'), 'evidence', type_='foreignkey')
    op.drop_index('uq_evidence_capture_key', table_name='evidence', postgresql_where=sa.text('capture_key IS NOT NULL'))
    op.drop_index('idx_evidence_field_mission_id', table_name='evidence')
    op.drop_column('evidence', 'capture_key')
    op.drop_column('evidence', 'field_mission_id')
    op.drop_index('idx_mission_member_mission_id', table_name='mission_member')
    op.drop_table('mission_member')
    op.drop_index('idx_mission_check_in_state', table_name='mission_check_in')
    op.drop_index('idx_mission_check_in_mission_id', table_name='mission_check_in')
    op.drop_table('mission_check_in')
    op.drop_index('idx_field_mission_status', table_name='field_mission')
    op.drop_index('idx_field_mission_search', table_name='field_mission', postgresql_using='gin')
    op.drop_index('idx_field_mission_organisation_id', table_name='field_mission')
    op.drop_index('idx_field_mission_geography_id', table_name='field_mission')
    op.drop_table('field_mission')

    bind = op.get_bind()
    SAFETY_STATE.drop(bind, checkfirst=True)
    MISSION_STATUS.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
