"""Configurable review workflows.

Spec section 36 asks for configurable workflows. An organisation defines the
review stages its content clears; the coarse lifecycle around them stays fixed
in code, deliberately, so that an organisation cannot redefine what
"published" means to the public by editing its own configuration.

The partial unique index allows many definitions per content type but only one
active: two active definitions would make "which workflow applies" ambiguous,
and that must never be ambiguous for an approval. Superseded definitions are
deactivated rather than deleted, because approval records point at their
stages and a trail that cannot say what was cleared is not a trail.

approval_record.workflow_stage_id is nullable: null means the single implicit
stage every organisation has before it configures anything, which is also what
every record approved before this migration cleared.

Revision ID: 64e1eeb65b12
Revises: c2b0d6a76a04
Create Date: 2026-09-18 14:49:54.272319

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e1eeb65b12'
down_revision: Union[str, None] = 'c2b0d6a76a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definition',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_workflow_definition_organisation_id_organisation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition'))
    )
    op.create_index('idx_workflow_organisation_id', 'workflow_definition', ['organisation_id'], unique=False)
    op.create_index('uq_workflow_active_per_type', 'workflow_definition', ['organisation_id', 'entity_type'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('workflow_stage',
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('required_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('requires_distinct_actor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_stage_definition_id_workflow_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage')),
    sa.UniqueConstraint('definition_id', 'position', name='uq_stage_position')
    )
    op.create_index('idx_stage_definition_id', 'workflow_stage', ['definition_id'], unique=False)
    op.add_column('approval_record', sa.Column('workflow_stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_approval_record_workflow_stage_id_workflow_stage'), 'approval_record', 'workflow_stage', ['workflow_stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_approval_record_workflow_stage_id_workflow_stage'), 'approval_record', type_='foreignkey')
    op.drop_column('approval_record', 'workflow_stage_id')
    op.drop_index('idx_stage_definition_id', table_name='workflow_stage')
    op.drop_table('workflow_stage')
    op.drop_index('uq_workflow_active_per_type', table_name='workflow_definition', postgresql_where=sa.text('is_active'))
    op.drop_index('idx_workflow_organisation_id', table_name='workflow_definition')
    op.drop_table('workflow_definition')
    # ### end Alembic commands ###
