"""readiness workflow

Give the scenario table a readiness workflow (spec sections 28-31): a playbook
made of ordered steps that each name a responsible role, rehearsals that record
what they found, and findings that hold a scenario's readiness down until
somebody other than the finder confirms they are closed.

Two hand-written adjustments to the autogenerated output:

* ``playbook_step.responsible_role`` reuses the existing ``role`` enum, which
  the baseline already created for ``user_organisation``. Autogenerate emitted
  it as a fresh ``sa.Enum``, which would try to CREATE TYPE a second time and
  fail. It is declared with ``create_type=False`` instead.
* The downgrade drops the two enum types this migration introduces.
  Autogenerate left them behind, so a down-then-up cycle would fail on the
  second CREATE TYPE.

``scenario.organisation_id`` becomes NOT NULL: readiness is something a
particular body is accountable for, and an ownerless scenario is a colour
nobody answers for. Nothing has ever written to this table — it had a model and
a search vector but no endpoints — so there is nothing to backfill, and the
ALTER fails loudly rather than inventing an owner if that turns out to be
wrong.

``scenario.status`` now defaults to RED rather than GREEN, but
that default is applied by the application rather than the database, so
existing rows keep the status they were given. This is deliberate: silently
downgrading a body's recorded readiness would be inventing a fact about them.
The floor is reported alongside the declared status on every read, so a stale
GREEN is visible as unsupported rather than quietly rewritten.

Revision ID: 72eb8f4f578f
Revises: ef262e3ed582
Create Date: 2026-09-18 23:30:27.953274

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '72eb8f4f578f'
down_revision: Union[str, None] = 'ef262e3ed582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DRILL_STATUS = sa.Enum("scheduled", "completed", "cancelled", name="drillstatus")
FINDING_SEVERITY = sa.Enum("observation", "minor", "major", "critical", name="findingseverity")

# Already created by the baseline for user_organisation.role. Referenced, not
# recreated.
EXISTING_ROLE = postgresql.ENUM(
    "super_admin",
    "executive",
    "editor",
    "evidence_manager",
    "researcher",
    "field_officer",
    "verifier",
    "integrity_analyst",
    "content_manager",
    "media_manager",
    "translator",
    "approver",
    "analyst",
    "public_user",
    name="role",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('status', DRILL_STATUS, nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conducted_by', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by'], ['user.id'], name=op.f('fk_drill_conducted_by_user')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_drill_scenario_id_scenario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill'))
    )
    op.create_index('idx_drill_scenario_id', 'drill', ['scenario_id'], unique=False)
    op.create_index('idx_drill_status', 'drill', ['status'], unique=False)
    op.create_table('playbook_step',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('responsible_role', EXISTING_ROLE, nullable=False),
    sa.Column('within_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name=op.f('fk_playbook_step_scenario_id_scenario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_step')),
    sa.UniqueConstraint('scenario_id', 'position', name='uq_playbook_step_position')
    )
    op.create_index('idx_playbook_step_scenario_id', 'playbook_step', ['scenario_id'], unique=False)
    op.create_table('drill_finding',
    sa.Column('drill_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', FINDING_SEVERITY, nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['drill_id'], ['drill.id'], name=op.f('fk_drill_finding_drill_id_drill'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['user.id'], name=op.f('fk_drill_finding_raised_by_user')),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], name=op.f('fk_drill_finding_resolved_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_finding'))
    )
    op.create_index('idx_drill_finding_drill_id', 'drill_finding', ['drill_id'], unique=False)
    op.create_index('idx_drill_finding_severity', 'drill_finding', ['severity'], unique=False)
    op.add_column('scenario', sa.Column('status_rationale', sa.Text(), nullable=True))
    op.add_column('scenario', sa.Column('status_declared_by', sa.UUID(), nullable=True))
    op.add_column('scenario', sa.Column('status_declared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scenario', sa.Column('geography_id', sa.UUID(), nullable=True))
    op.add_column('scenario', sa.Column('drill_interval_days', sa.Integer(), nullable=True))
    op.alter_column('scenario', 'organisation_id', existing_type=sa.UUID(), nullable=False)
    op.create_index('idx_scenario_organisation_id', 'scenario', ['organisation_id'], unique=False)
    op.create_foreign_key(op.f('fk_scenario_status_declared_by_user'), 'scenario', 'user', ['status_declared_by'], ['id'])
    op.create_foreign_key(op.f('fk_scenario_geography_id_geographic_area'), 'scenario', 'geographic_area', ['geography_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scenario_geography_id_geographic_area'), 'scenario', type_='foreignkey')
    op.drop_constraint(op.f('fk_scenario_status_declared_by_user'), 'scenario', type_='foreignkey')
    op.drop_index('idx_scenario_organisation_id', table_name='scenario')
    op.alter_column('scenario', 'organisation_id', existing_type=sa.UUID(), nullable=True)
    op.drop_column('scenario', 'drill_interval_days')
    op.drop_column('scenario', 'geography_id')
    op.drop_column('scenario', 'status_declared_at')
    op.drop_column('scenario', 'status_declared_by')
    op.drop_column('scenario', 'status_rationale')
    op.drop_index('idx_drill_finding_severity', table_name='drill_finding')
    op.drop_index('idx_drill_finding_drill_id', table_name='drill_finding')
    op.drop_table('drill_finding')
    op.drop_index('idx_playbook_step_scenario_id', table_name='playbook_step')
    op.drop_table('playbook_step')
    op.drop_index('idx_drill_status', table_name='drill')
    op.drop_index('idx_drill_scenario_id', table_name='drill')
    op.drop_table('drill')

    bind = op.get_bind()
    FINDING_SEVERITY.drop(bind, checkfirst=True)
    DRILL_STATUS.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
