"""information integrity workflow

Give integrity_signal the lifecycle spec sections 25-26 describe. The table
existed from the baseline but nothing ever read or wrote it, so it had a
free-text status with no transitions and no way to record what was found out
about a claim or what it rested on.

Two hand-written adjustments to the autogenerated output, both of which matter:

* The status column becomes an enum with an explicit ``USING`` clause.
  PostgreSQL will not cast varchar to an enum on its own, so the autogenerated
  ``ALTER`` would have failed on any database that had the column at all.
* ``verification_result`` is **renamed** to ``assessment`` rather than dropped
  and recreated. Autogenerate proposed a drop and an add, which loses whatever
  a column holds. The meaning is the same — the written reasoning behind a
  finding — and the rename keeps it.

``organisation_id`` becomes NOT NULL. A signal is logged by a member of staff
who already belongs to a body, so there is no state in which it belongs to
nobody. If any row somehow holds a null the migration fails loudly here, which
is the right outcome: a silent backfill would invent an owner for a record
whose owner is unknown.

Revision ID: ef262e3ed582
Revises: 64e1eeb65b12
Create Date: 2026-09-18 15:27:41.370294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef262e3ed582"
down_revision: Union[str, None] = "64e1eeb65b12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SIGNAL_STATUS = sa.Enum(
    "new",
    "assessing",
    "assessed",
    "approved",
    "published",
    "withdrawn",
    "closed",
    name="integritysignalstatus",
)

FINDING = sa.Enum(
    "accurate",
    "misleading",
    "out_of_context",
    "false",
    "unsubstantiated",
    "unresolved",
    name="integrityfinding",
)

# Kept identical to models.core._search_vector's output for this table. A
# difference here is drift alembic check would catch, so it is written once and
# compared, not paraphrased.
SEARCH_VECTOR = (
    "setweight(to_tsvector('english', coalesce(\"claim\", '')), 'A') || "
    "setweight(to_tsvector('english', coalesce(\"assessment\", '')), 'B') || "
    "setweight(to_tsvector('english', coalesce(\"response\", '')), 'B') || "
    "setweight(to_tsvector('english', coalesce(\"circulation\", '')), 'C')"
)


def upgrade() -> None:
    bind = op.get_bind()
    SIGNAL_STATUS.create(bind, checkfirst=True)
    FINDING.create(bind, checkfirst=True)

    # The reasoning behind a finding, under a name that no longer reads like
    # the finding itself.
    op.alter_column("integrity_signal", "verification_result", new_column_name="assessment")

    op.add_column("integrity_signal", sa.Column("circulation", sa.Text(), nullable=True))
    op.add_column("integrity_signal", sa.Column("first_observed", sa.Date(), nullable=True))
    op.add_column(
        "integrity_signal",
        sa.Column("language", sa.String(length=5), nullable=False, server_default="en"),
    )
    op.add_column("integrity_signal", sa.Column("geography_id", sa.UUID(), nullable=True))
    op.add_column("integrity_signal", sa.Column("thematic_area_id", sa.UUID(), nullable=True))
    op.add_column("integrity_signal", sa.Column("finding", FINDING, nullable=True))
    op.add_column("integrity_signal", sa.Column("impact", sa.Text(), nullable=True))
    op.add_column("integrity_signal", sa.Column("evidence_id", sa.UUID(), nullable=True))
    op.add_column("integrity_signal", sa.Column("assessed_by", sa.UUID(), nullable=True))
    op.add_column(
        "integrity_signal", sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "integrity_signal", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "integrity_signal", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "integrity_signal",
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
    )

    # The application owns these defaults; the server default exists only so
    # the NOT NULL columns can be added to a table that already has rows.
    op.alter_column("integrity_signal", "language", server_default=None)
    op.alter_column("integrity_signal", "version", server_default=None)

    op.add_column(
        "integrity_signal",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(SEARCH_VECTOR, persisted=True),
            nullable=True,
        ),
    )

    op.alter_column("integrity_signal", "organisation_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "integrity_signal",
        "status",
        existing_type=sa.VARCHAR(length=50),
        type_=SIGNAL_STATUS,
        existing_nullable=False,
        postgresql_using="status::integritysignalstatus",
    )

    op.create_index(
        "idx_integrity_geography_id", "integrity_signal", ["geography_id"], unique=False
    )
    op.create_index(
        "idx_integrity_organisation_id", "integrity_signal", ["organisation_id"], unique=False
    )
    op.create_index(
        "idx_integrity_search",
        "integrity_signal",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_foreign_key(
        op.f("fk_integrity_signal_evidence_id_evidence"),
        "integrity_signal",
        "evidence",
        ["evidence_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_integrity_signal_thematic_area_id_thematic_area"),
        "integrity_signal",
        "thematic_area",
        ["thematic_area_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_integrity_signal_assessed_by_user"),
        "integrity_signal",
        "user",
        ["assessed_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_integrity_signal_geography_id_geographic_area"),
        "integrity_signal",
        "geographic_area",
        ["geography_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_integrity_signal_geography_id_geographic_area"),
        "integrity_signal",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_integrity_signal_assessed_by_user"), "integrity_signal", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_integrity_signal_thematic_area_id_thematic_area"),
        "integrity_signal",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_integrity_signal_evidence_id_evidence"), "integrity_signal", type_="foreignkey"
    )
    op.drop_index("idx_integrity_search", table_name="integrity_signal", postgresql_using="gin")
    op.drop_index("idx_integrity_organisation_id", table_name="integrity_signal")
    op.drop_index("idx_integrity_geography_id", table_name="integrity_signal")

    op.alter_column(
        "integrity_signal",
        "status",
        existing_type=SIGNAL_STATUS,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using="status::text",
    )
    op.alter_column("integrity_signal", "organisation_id", existing_type=sa.UUID(), nullable=True)

    op.drop_column("integrity_signal", "search_vector")
    op.drop_column("integrity_signal", "version")
    op.drop_column("integrity_signal", "published_at")
    op.drop_column("integrity_signal", "approved_at")
    op.drop_column("integrity_signal", "assessed_at")
    op.drop_column("integrity_signal", "assessed_by")
    op.drop_column("integrity_signal", "evidence_id")
    op.drop_column("integrity_signal", "impact")
    op.drop_column("integrity_signal", "finding")
    op.drop_column("integrity_signal", "thematic_area_id")
    op.drop_column("integrity_signal", "geography_id")
    op.drop_column("integrity_signal", "language")
    op.drop_column("integrity_signal", "first_observed")
    op.drop_column("integrity_signal", "circulation")

    op.alter_column("integrity_signal", "assessment", new_column_name="verification_result")

    bind = op.get_bind()
    FINDING.drop(bind, checkfirst=True)
    SIGNAL_STATUS.drop(bind, checkfirst=True)
